const MOCK_TRACKLISTS = [
  {
    id: 'tl-001',
    title: 'TECHNO RITUAL VOL. 4',
    sourceFormat: 'rekordbox',
    rawFilePath: null,
    preset: 'dark',
    visibleFields: ['title', 'artist', 'bpm', 'key', 'durationSecs'],
    bgMode: 'solid',
    bgValue: null,
    maxTracks: 47,
    trackRangeStart: null,
    trackRangeEnd: null,
    createdAt: '2026-03-29T22:00:00Z',
    updatedAt: '2026-03-29T23:45:00Z',
  },
  {
    id: 'tl-002',
    title: 'TRESOR CLOSING SET',
    sourceFormat: 'rekordbox',
    rawFilePath: null,
    preset: 'dark',
    visibleFields: ['title', 'artist', 'bpm', 'key', 'durationSecs'],
    bgMode: 'solid',
    bgValue: null,
    maxTracks: 31,
    trackRangeStart: null,
    trackRangeEnd: null,
    createdAt: '2026-03-08T02:00:00Z',
    updatedAt: '2026-03-08T04:30:00Z',
  },
  {
    id: 'tl-003',
    title: 'STUDIO WARMUP SESSION',
    sourceFormat: 'serato',
    rawFilePath: null,
    preset: 'dark',
    visibleFields: ['title', 'artist', 'bpm', 'key', 'durationSecs'],
    bgMode: 'solid',
    bgValue: null,
    maxTracks: 18,
    trackRangeStart: null,
    trackRangeEnd: null,
    createdAt: '2026-03-02T14:00:00Z',
    updatedAt: '2026-03-02T16:00:00Z',
  },
  {
    id: 'tl-004',
    title: 'FABRIC ROOM 1 PREP',
    sourceFormat: 'traktor',
    rawFilePath: null,
    preset: 'dark',
    visibleFields: ['title', 'artist', 'bpm', 'key', 'durationSecs'],
    bgMode: 'solid',
    bgValue: null,
    maxTracks: 60,
    trackRangeStart: null,
    trackRangeEnd: null,
    createdAt: '2026-02-18T10:00:00Z',
    updatedAt: '2026-02-18T11:30:00Z',
  },
]

export default defineEventHandler(() => {
  return { tracklists: MOCK_TRACKLISTS }
})
