package rider

import (
	"bytes"
	"fmt"
	"strconv"
	"strings"
	"time"

	"codeberg.org/go-pdf/fpdf"
	"github.com/klubhub/dj/api/internal/settings"
)

// headingInkR/G/B are the dark-ink RGB values for section headings. The
// accent colour is too light to read as body text on a white page
// (matches EPK's choice in epk/pdf.go).
const headingInkR, headingInkG, headingInkB = 26, 26, 26

// tr converts UTF-8 to cp1252 (fpdf's built-in core font encoding).
// Same workaround as epk/pdf.go for non-ASCII glyphs. Embedded UTF-8
// fonts are a future improvement; for v1 the rider text is plain ASCII
// or simple Latin-1 which fits the existing encoding.
var tr = fpdf.New("P", "mm", "A4", "").UnicodeTranslatorFromDescriptor("")

// renderRiderPDF generates a one-page A4 portrait PDF for a per-gig
// rider copy. The PDF has:
//
//   - Header: DJ name (uppercase), accent rule
//   - Venue line: "<Venue> — <City, Country>" + long date
//   - Four sections: TECHNICAL / HOSPITALITY / BACKLINE / OTHER NOTES
//     in that fixed order. Empty sections are skipped.
//   - Footer: "Generated by KlubHub DJ" + accent hairline.
//
// The accent colour is read from userSettings.DefaultColors["primary"],
// falling back to "#96F8FF" (the project's default cyan).
func renderRiderPDF(
	att *RiderAttachment,
	venueName, venueCity, venueCountry string,
	gigDate time.Time,
	userSettings *settings.UserSettings,
	buf *bytes.Buffer,
) error {
	f := fpdf.New("P", "mm", "A4", "")
	f.SetMargins(20, 20, 20)
	f.SetAutoPageBreak(true, 20)
	f.AddPage()

	// Resolve accent colour.
	accentHex := "#96F8FF"
	if userSettings != nil && userSettings.DefaultColors != nil {
		if v, ok := userSettings.DefaultColors["primary"]; ok {
			if s, ok := v.(string); ok && s != "" {
				accentHex = s
			}
		}
	}
	ar, ag, ab := hexToRGB(accentHex)

	// Footer: hairline + caption, drawn by fpdf's footer hook. It runs outside
	// the auto-page-break check, so it cannot spill onto an extra page (the old
	// inline footer started below the 277mm break trigger, so even a one-line
	// rider produced a second page holding only the caption), and it repeats on
	// every page of a long rider.
	f.SetFooterFunc(func() {
		f.SetDrawColor(ar, ag, ab)
		f.SetLineWidth(0.2)
		y := 280.0 // near A4 bottom (297mm)
		f.Line(20, y, 190, y)
		f.SetXY(20, y+2)
		f.SetFont("Helvetica", "I", 8)
		f.SetTextColor(120, 120, 120)
		f.MultiCell(0, 4, tr("Generated by KlubHub DJ"), "", "L", false)
	})

	// ── Header: DJ name (uppercase) + accent rule ───────────────────
	djName := ""
	if userSettings != nil {
		djName = userSettings.DJName
	}
	if djName == "" {
		djName = "ARTIST"
	}
	f.SetFont("Helvetica", "B", 18)
	f.SetTextColor(headingInkR, headingInkG, headingInkB)
	f.MultiCell(0, 12, tr(strings.ToUpper(djName)), "", "L", false)
	f.SetDrawColor(ar, ag, ab)
	f.SetLineWidth(0.8)
	f.Line(20, f.GetY(), 190, f.GetY())
	f.Ln(6)

	// ── Venue line ──────────────────────────────────────────────────
	venueParts := []string{}
	if venueName != "" {
		venueParts = append(venueParts, venueName)
	}
	cityCountry := strings.TrimSpace(strings.Join([]string{venueCity, venueCountry}, ", "))
	if cityCountry != "" {
		venueParts = append(venueParts, cityCountry)
	}
	venueLine := strings.Join(venueParts, " — ")
	if venueLine == "" {
		venueLine = "Venue TBA"
	}

	f.SetFont("Helvetica", "", 11)
	f.SetTextColor(headingInkR, headingInkG, headingInkB)
	f.MultiCell(0, 6, tr(venueLine), "", "L", false)

	dateLine := formatLongDate(gigDate)
	if dateLine != "" {
		f.SetFont("Helvetica", "", 10)
		f.SetTextColor(80, 80, 80)
		f.MultiCell(0, 5, tr(dateLine), "", "L", false)
	}

	// Hairline below venue/date block.
	f.SetDrawColor(ar, ag, ab)
	f.SetLineWidth(0.3)
	f.Line(20, f.GetY()+2, 190, f.GetY()+2)
	f.Ln(8)

	// ── Four sections in fixed order ────────────────────────────────
	sections := []struct {
		Label string
		Body  string
	}{
		{"TECHNICAL", att.Technical},
		{"HOSPITALITY", att.Hospitality},
		{"BACKLINE", att.Backline},
		{"OTHER NOTES", att.OtherNotes},
	}
	for _, s := range sections {
		if isBlank(s.Body) {
			continue
		}
		writeRiderSectionHeading(f, s.Label, ar, ag, ab)
		f.SetFont("Helvetica", "", 10)
		f.SetTextColor(headingInkR, headingInkG, headingInkB)
		f.MultiCell(0, 5, tr(s.Body), "", "L", false)
		f.Ln(3)
	}

	return f.Output(buf)
}

// writeRiderSectionHeading renders an ALL_CAPS section heading in dark
// ink followed by a thin accent rule. Same visual pattern as EPK's
// writeSectionHeading but without the per-section rule width overrides.
func writeRiderSectionHeading(f *fpdf.Fpdf, title string, r, g, b int) {
	f.SetFont("Helvetica", "B", 11)
	f.SetTextColor(headingInkR, headingInkG, headingInkB)
	f.MultiCell(0, 8, tr(title), "", "L", false)
	f.SetDrawColor(r, g, b)
	f.SetLineWidth(0.3)
	f.Line(20, f.GetY(), 190, f.GetY())
	f.Ln(4)
}

// formatLongDate renders a gig date in "Saturday, 14 March 2026" form.
// Returns an empty string when the date is the zero value (signals "no
// gig date resolved" so the renderer can omit the line).
func formatLongDate(t time.Time) string {
	if t.IsZero() {
		return ""
	}
	return t.Format("Monday, 2 January 2006")
}

// hexToRGB converts a hex colour string ("#RRGGBB" or "RRGGBB") to
// 0-255 RGB components. Falls back to (150, 248, 255) on parse error —
// same fallback EPK uses.
func hexToRGB(hex string) (int, int, int) {
	hex = strings.TrimPrefix(hex, "#")
	if len(hex) != 6 {
		return 150, 248, 255
	}
	r, err1 := strconv.ParseInt(hex[0:2], 16, 32)
	g, err2 := strconv.ParseInt(hex[2:4], 16, 32)
	b, err3 := strconv.ParseInt(hex[4:6], 16, 32)
	if err1 != nil || err2 != nil || err3 != nil {
		return 150, 248, 255
	}
	return int(r), int(g), int(b)
}

// ensure fmt is used by the package even if other files stop referencing
// it — keeps gofmt / goimports from stripping the import on edits.
var _ = fmt.Sprintf