package finance

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

type EntryRepository struct{ pool *pgxpool.Pool }

func NewEntryRepository(pool *pgxpool.Pool) *EntryRepository { return &EntryRepository{pool: pool} }

const entryColumns = `id, kind, amount_minor, currency, category, entry_date::text, description, notes,
	gig_id, status, auto_generated, source_kind, source_id, source_amount_minor, source_currency,
	source_description, created_at, updated_at, deleted_at`

func entryScan(e *Entry) []any {
	return []any{&e.ID, &e.Kind, &e.AmountMinor, &e.Currency, &e.Category, &e.EntryDate,
		&e.Description, &e.Notes, &e.GigID, &e.Status, &e.AutoGenerated, &e.SourceKind,
		&e.SourceID, &e.SourceAmountMinor, &e.SourceCurrency, &e.SourceDescription,
		&e.CreatedAt, &e.UpdatedAt, &e.DeletedAt}
}

func (r *EntryRepository) Create(ctx context.Context, req CreateEntryRequest) (*Entry, error) {
	var e Entry
	err := r.pool.QueryRow(ctx, `INSERT INTO finance_entries
		(kind, amount_minor, currency, category, entry_date, description, notes, gig_id)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING `+entryColumns,
		req.Kind, req.AmountMinor, req.Currency, req.Category, req.EntryDate, req.Description, req.Notes, req.GigID).Scan(entryScan(&e)...)
	if err != nil {
		if isEntryGigFKViolation(err) {
			return nil, EntryValidationErrors{{Field: "gig_id", Message: "does not reference an existing gig"}}
		}
		return nil, fmt.Errorf("create finance entry: %w", err)
	}
	return &e, nil
}

func (r *EntryRepository) CreateGenerated(ctx context.Context, in GeneratedEntryInput) (*Entry, error) {
	// The (source_kind, source_id, kind) partial unique index covers only
	// active, not-deleted rows; once a generated row is voided or
	// deleted, the partial index no longer protects the slot. Probe the
	// source first so any retry against an inactive prior row surfaces
	// as ErrGeneratedEntryConflict instead of silently creating a
	// duplicate revenue stream. Callers that legitimately need to
	// replace a voided/deleted row (e.g. the FIN-05 reversal flow after
	// the user explicitly chose delete/void and then re-paid the gig)
	// go through the gig payment transition processor, which has its
	// own replacement-aware path.
	if existing, err := r.GetByGeneratedSource(ctx, in.SourceKind, in.SourceID, in.Kind); err == nil {
		if !sameGeneratedIdentity(existing, in) {
			return nil, ErrGeneratedEntryConflict
		}
		return existing, nil
	} else if !errors.Is(err, ErrEntryNotFound) {
		if isEntryGigFKViolation(err) {
			return nil, EntryValidationErrors{{Field: "gig_id", Message: "does not reference an existing gig"}}
		}
		return nil, fmt.Errorf("lookup existing generated entry: %w", err)
	}

	var e Entry
	err := r.pool.QueryRow(ctx, `INSERT INTO finance_entries
		(kind, amount_minor, currency, category, entry_date, description, notes, gig_id,
		 auto_generated, source_kind, source_id, source_amount_minor, source_currency, source_description)
		VALUES ($1,$2,$3,$4,$5,$6,$7,$8,true,$9,$10,$11,$12,$13)
		RETURNING `+entryColumns,
		in.Kind, in.AmountMinor, in.Currency, in.Category, in.EntryDate, in.Description, in.Notes,
		in.GigID, in.SourceKind, in.SourceID, in.SourceAmountMinor, in.SourceCurrency, in.SourceDescription).Scan(entryScan(&e)...)
	if err == nil {
		return &e, nil
	}
	if !isUniqueViolation(err) {
		if isEntryGigFKViolation(err) {
			return nil, EntryValidationErrors{{Field: "gig_id", Message: "does not reference an existing gig"}}
		}
		return nil, fmt.Errorf("create generated finance entry: %w", err)
	}
	// The partial unique index tripped because a concurrent writer just
	// inserted the same source. Re-read and reuse the matching row.
	existing, getErr := r.GetByGeneratedSource(ctx, in.SourceKind, in.SourceID, in.Kind)
	if getErr != nil {
		if isEntryGigFKViolation(getErr) {
			return nil, EntryValidationErrors{{Field: "gig_id", Message: "does not reference an existing gig"}}
		}
		return nil, fmt.Errorf("lookup existing generated entry: %w", getErr)
	}
	if !sameGeneratedIdentity(existing, in) {
		return nil, ErrGeneratedEntryConflict
	}
	return existing, nil
}

// sameGeneratedIdentity compares the persistent fields of an existing
// generated row to the requested payload. Used to distinguish idempotent
// retries from mismatched retries when the partial unique index fires.
func sameGeneratedIdentity(existing *Entry, in GeneratedEntryInput) bool {
	if existing == nil {
		return false
	}
	if existing.Status != EntryStatusActive || existing.DeletedAt != nil {
		return false
	}
	if existing.AmountMinor != in.AmountMinor ||
		existing.Currency != in.Currency ||
		existing.Category != in.Category ||
		existing.EntryDate != in.EntryDate ||
		existing.Description != in.Description ||
		existing.Notes != in.Notes ||
		existing.AutoGenerated != true ||
		existing.SourceKind != in.SourceKind {
		return false
	}
	if existing.SourceID == nil || *existing.SourceID != in.SourceID {
		return false
	}
	if !uuidPtrEqual(existing.GigID, in.GigID) {
		return false
	}
	if !int64PtrEqual(existing.SourceAmountMinor, in.SourceAmountMinor) {
		return false
	}
	if !stringPtrEqual(existing.SourceCurrency, in.SourceCurrency) {
		return false
	}
	return existing.SourceDescription == in.SourceDescription
}

func uuidPtrEqual(a, b *uuid.UUID) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}

func int64PtrEqual(a, b *int64) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}

func stringPtrEqual(a, b *string) bool {
	if a == nil || b == nil {
		return a == b
	}
	return *a == *b
}

func (r *EntryRepository) Get(ctx context.Context, id uuid.UUID) (*Entry, error) {
	return r.get(ctx, id, false)
}

func (r *EntryRepository) GetIncludingInactive(ctx context.Context, id uuid.UUID) (*Entry, error) {
	return r.get(ctx, id, true)
}

func (r *EntryRepository) get(ctx context.Context, id uuid.UUID, includeDeleted bool) (*Entry, error) {
	var e Entry
	q := `SELECT ` + entryColumns + ` FROM finance_entries WHERE id=$1`
	if !includeDeleted {
		q += ` AND deleted_at IS NULL`
	}
	err := r.pool.QueryRow(ctx, q, id).Scan(entryScan(&e)...)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrEntryNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get finance entry: %w", err)
	}
	return &e, nil
}

func (r *EntryRepository) GetByGeneratedSource(ctx context.Context, sourceKind EntrySourceKind, sourceID uuid.UUID, kind EntryKind) (*Entry, error) {
	var e Entry
	err := r.pool.QueryRow(ctx, `SELECT `+entryColumns+` FROM finance_entries
		WHERE auto_generated=true AND source_kind=$1 AND source_id=$2 AND kind=$3`, sourceKind, sourceID, kind).Scan(entryScan(&e)...)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrEntryNotFound
	}
	if err != nil {
		return nil, fmt.Errorf("get generated finance entry: %w", err)
	}
	return &e, nil
}

func (r *EntryRepository) ListByGig(ctx context.Context, gigID uuid.UUID) ([]*Entry, error) {
	return r.List(ctx, EntryFilter{GigID: &gigID})
}

func (r *EntryRepository) List(ctx context.Context, f EntryFilter) ([]*Entry, error) {
	rows, err := r.pool.Query(ctx, `SELECT `+entryColumns+` FROM finance_entries
		WHERE deleted_at IS NULL
		  AND ($1='' OR kind=$1)
		  AND ($2='' OR status=$2)
		  AND ($3='' OR currency=$3)
		  AND ($4='' OR category=$4)
		  AND ($5::uuid IS NULL OR gig_id=$5)
		  AND ($6='' OR entry_date >= $6::date)
		  AND ($7='' OR entry_date < $7::date)
		ORDER BY entry_date DESC, created_at DESC, id DESC`, f.Kind, f.Status, f.Currency, f.Category, f.GigID, f.From, f.To)
	if err != nil {
		return nil, fmt.Errorf("list finance entries: %w", err)
	}
	defer rows.Close()
	entries := make([]*Entry, 0)
	for rows.Next() {
		var e Entry
		if err := rows.Scan(entryScan(&e)...); err != nil {
			return nil, fmt.Errorf("scan finance entry: %w", err)
		}
		entries = append(entries, &e)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("list finance entries: %w", err)
	}
	return entries, nil
}

func (r *EntryRepository) Update(ctx context.Context, id uuid.UUID, req UpdateEntryRequest) (*Entry, error) {
	var e Entry
	err := r.pool.QueryRow(ctx, `UPDATE finance_entries SET
		kind=$2, amount_minor=$3, currency=$4, category=$5, entry_date=$6,
		description=$7, notes=$8, gig_id=$9, updated_at=clock_timestamp()
		WHERE id=$1 AND updated_at=$10 AND deleted_at IS NULL AND status='active' AND auto_generated=false
		RETURNING `+entryColumns, id, req.Kind, req.AmountMinor, req.Currency, req.Category,
		req.EntryDate, req.Description, req.Notes, req.GigID, req.UpdatedAt).Scan(entryScan(&e)...)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, r.mutationError(ctx, id)
	}
	if err != nil {
		if isEntryGigFKViolation(err) {
			return nil, EntryValidationErrors{{Field: "gig_id", Message: "does not reference an existing gig"}}
		}
		return nil, fmt.Errorf("update finance entry: %w", err)
	}
	return &e, nil
}

func (r *EntryRepository) Delete(ctx context.Context, id uuid.UUID, updatedAt time.Time) error {
	tag, err := r.pool.Exec(ctx, `UPDATE finance_entries SET deleted_at=clock_timestamp(), updated_at=clock_timestamp()
		WHERE id=$1 AND updated_at=$2 AND deleted_at IS NULL AND status='active' AND auto_generated=false`, id, updatedAt)
	if err != nil {
		return fmt.Errorf("delete finance entry: %w", err)
	}
	if tag.RowsAffected() == 0 {
		return r.mutationError(ctx, id)
	}
	return nil
}

func (r *EntryRepository) Void(ctx context.Context, id uuid.UUID, updatedAt time.Time) (*Entry, error) {
	var e Entry
	err := r.pool.QueryRow(ctx, `UPDATE finance_entries SET status='voided', updated_at=clock_timestamp()
		WHERE id=$1 AND updated_at=$2 AND deleted_at IS NULL AND status='active'
		RETURNING `+entryColumns, id, updatedAt).Scan(entryScan(&e)...)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, r.mutationError(ctx, id)
	}
	if err != nil {
		return nil, fmt.Errorf("void finance entry: %w", err)
	}
	return &e, nil
}

func (r *EntryRepository) mutationError(ctx context.Context, id uuid.UUID) error {
	var auto bool
	var status EntryStatus
	err := r.pool.QueryRow(ctx, `SELECT auto_generated, status FROM finance_entries WHERE id=$1 AND deleted_at IS NULL`, id).Scan(&auto, &status)
	if errors.Is(err, pgx.ErrNoRows) {
		return ErrEntryNotFound
	}
	if err != nil {
		return fmt.Errorf("classify finance entry mutation: %w", err)
	}
	if auto {
		return ErrEntryImmutable
	}
	if status != EntryStatusActive {
		return ErrEntryInactive
	}
	return ErrEntryConflict
}

func isEntryGigFKViolation(err error) bool {
	var pgErr *pgconn.PgError
	return errors.As(err, &pgErr) && pgErr.Code == "23503" && pgErr.ConstraintName == "finance_entries_gig_id_fkey"
}

func (r *EntryRepository) Summary(ctx context.Context, dr DateRange, gigID *uuid.UUID) (map[string]EntryTotals, error) {
	rows, err := r.pool.Query(ctx, `SELECT currency,
		COALESCE(SUM(amount_minor) FILTER (WHERE kind='income'),0),
		COALESCE(SUM(amount_minor) FILTER (WHERE kind='expense'),0)
		FROM finance_entries
		WHERE deleted_at IS NULL AND status='active'
		  AND ($1='' OR entry_date >= $1::date)
		  AND ($2='' OR entry_date < $2::date)
		  AND ($3::uuid IS NULL OR gig_id=$3)
		GROUP BY currency ORDER BY currency`, dr.From, dr.To, gigID)
	if err != nil {
		return nil, fmt.Errorf("summarize finance entries: %w", err)
	}
	defer rows.Close()
	out := make(map[string]EntryTotals)
	for rows.Next() {
		var v EntryTotals
		if err := rows.Scan(&v.Currency, &v.IncomeMinor, &v.ExpenseMinor); err != nil {
			return nil, fmt.Errorf("scan finance summary: %w", err)
		}
		out[v.Currency] = v
	}
	return out, rows.Err()
}
