package finance

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
)

type EntryKind string

const (
	EntryKindIncome  EntryKind = "income"
	EntryKindExpense EntryKind = "expense"
)

func (k EntryKind) IsValid() bool { return k == EntryKindIncome || k == EntryKindExpense }

type EntryStatus string

const (
	EntryStatusActive EntryStatus = "active"
	EntryStatusVoided EntryStatus = "voided"
)

func (s EntryStatus) IsValid() bool { return s == EntryStatusActive || s == EntryStatusVoided }

type EntrySourceKind string

const (
	EntrySourceManual         EntrySourceKind = "manual"
	EntrySourceGigPayment     EntrySourceKind = "gig_payment"
	EntrySourceInvoicePayment EntrySourceKind = "invoice_payment"
)

func (s EntrySourceKind) IsValid() bool {
	return s == EntrySourceManual || s == EntrySourceGigPayment || s == EntrySourceInvoicePayment
}

type Entry struct {
	ID                uuid.UUID       `json:"id"`
	Kind              EntryKind       `json:"kind"`
	AmountMinor       int64           `json:"amount_minor"`
	Currency          string          `json:"currency"`
	Category          string          `json:"category"`
	EntryDate         string          `json:"entry_date"`
	Description       string          `json:"description"`
	Notes             string          `json:"notes"`
	GigID             *uuid.UUID      `json:"gig_id"`
	Status            EntryStatus     `json:"status"`
	AutoGenerated     bool            `json:"auto_generated"`
	SourceKind        EntrySourceKind `json:"source_kind"`
	SourceID          *uuid.UUID      `json:"source_id"`
	SourceAmountMinor *int64          `json:"source_amount_minor"`
	SourceCurrency    *string         `json:"source_currency"`
	SourceDescription string          `json:"source_description"`
	CreatedAt         time.Time       `json:"created_at"`
	UpdatedAt         time.Time       `json:"updated_at"`
	DeletedAt         *time.Time      `json:"deleted_at"`
	// AttachmentCount is the number of receipt files on the entry; read paths
	// fill it, so a row can show a paperclip without fetching the files.
	AttachmentCount int `json:"attachment_count"`
}

// ReceiptFilter narrows a list by receipt files.
//
//	missing  active EXPENSES with no files: the ones that still need a receipt.
//	         Income (gig payments, royalties) and voided entries are never
//	         "missing" (a voided entry can no longer take files).
//	present  any entry with at least one file.
type ReceiptFilter string

const (
	ReceiptAny     ReceiptFilter = ""
	ReceiptMissing ReceiptFilter = "missing"
	ReceiptPresent ReceiptFilter = "present"
)

// IsValid reports whether f is a known receipt filter.
func (f ReceiptFilter) IsValid() bool {
	return f == ReceiptAny || f == ReceiptMissing || f == ReceiptPresent
}

type CreateEntryRequest struct {
	Kind        EntryKind  `json:"kind"`
	AmountMinor int64      `json:"amount_minor"`
	Currency    string     `json:"currency"`
	Category    string     `json:"category"`
	EntryDate   string     `json:"entry_date"`
	Description string     `json:"description"`
	Notes       string     `json:"notes"`
	GigID       *uuid.UUID `json:"gig_id"`
}

type UpdateEntryRequest struct {
	Kind        EntryKind  `json:"kind"`
	AmountMinor int64      `json:"amount_minor"`
	Currency    string     `json:"currency"`
	Category    string     `json:"category"`
	EntryDate   string     `json:"entry_date"`
	Description string     `json:"description"`
	Notes       string     `json:"notes"`
	GigID       *uuid.UUID `json:"gig_id"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type GeneratedEntryInput struct {
	Kind              EntryKind
	AmountMinor       int64
	Currency          string
	Category          string
	EntryDate         string
	Description       string
	Notes             string
	GigID             *uuid.UUID
	SourceKind        EntrySourceKind
	SourceID          uuid.UUID
	SourceAmountMinor *int64
	SourceCurrency    *string
	SourceDescription string
}

type EntryFilter struct {
	Kind     EntryKind
	Status   EntryStatus
	Currency string
	Category string
	GigID    *uuid.UUID
	From     string
	To       string
	Receipt  ReceiptFilter
}

type DateRange struct {
	From string `json:"from"`
	To   string `json:"to"`
}

func (r DateRange) Validate() error {
	from, err := parseEntryDate(r.From)
	if err != nil {
		return EntryValidationErrors{{Field: "from", Message: "must be YYYY-MM-DD"}}
	}
	to, err := parseEntryDate(r.To)
	if err != nil {
		return EntryValidationErrors{{Field: "to", Message: "must be YYYY-MM-DD"}}
	}
	if !from.Before(to) {
		return EntryValidationErrors{{Field: "to", Message: "must be after from (exclusive upper bound)"}}
	}
	return nil
}

type EntryTotals struct {
	Currency     string `json:"currency"`
	IncomeMinor  int64  `json:"income_minor"`
	ExpenseMinor int64  `json:"expense_minor"`
}

type SummaryScope string

const (
	SummaryScopeMonth SummaryScope = "month"
	SummaryScopeYear  SummaryScope = "year"
)

type SummaryFilter struct {
	Scope SummaryScope
	Year  int
	Month int
}

func (f SummaryFilter) DateRange() (DateRange, error) {
	switch f.Scope {
	case SummaryScopeMonth:
		if f.Year < 1 || f.Month < 1 || f.Month > 12 {
			return DateRange{}, EntryValidationErrors{{Field: "month", Message: "year and month are required"}}
		}
		from := time.Date(f.Year, time.Month(f.Month), 1, 0, 0, 0, 0, time.UTC)
		return DateRange{From: from.Format("2006-01-02"), To: from.AddDate(0, 1, 0).Format("2006-01-02")}, nil
	case SummaryScopeYear:
		if f.Year < 1 {
			return DateRange{}, EntryValidationErrors{{Field: "year", Message: "is required"}}
		}
		from := time.Date(f.Year, 1, 1, 0, 0, 0, 0, time.UTC)
		return DateRange{From: from.Format("2006-01-02"), To: from.AddDate(1, 0, 0).Format("2006-01-02")}, nil
	default:
		return DateRange{}, EntryValidationErrors{{Field: "scope", Message: "must be month or year"}}
	}
}

type ProfitLossTotals struct {
	Currency        string `json:"currency"`
	IncomeMinor     int64  `json:"income_minor"`
	ExpenseMinor    int64  `json:"expense_minor"`
	ProfitLossMinor int64  `json:"profit_loss_minor"`
}

type ProfitLossScope string

const (
	ProfitLossScopeGig   ProfitLossScope = "gig"
	ProfitLossScopeMonth ProfitLossScope = "month"
	ProfitLossScopeYear  ProfitLossScope = "year"
)

type ProfitLossFilter struct {
	Scope ProfitLossScope
	GigID *uuid.UUID
	Year  int
	Month int
}

func (f ProfitLossFilter) DateRange() (DateRange, error) {
	switch f.Scope {
	case ProfitLossScopeMonth:
		if f.Year < 1 || f.Month < 1 || f.Month > 12 {
			return DateRange{}, EntryValidationErrors{{Field: "month", Message: "year and month are required"}}
		}
		from := time.Date(f.Year, time.Month(f.Month), 1, 0, 0, 0, 0, time.UTC)
		return DateRange{From: from.Format("2006-01-02"), To: from.AddDate(0, 1, 0).Format("2006-01-02")}, nil
	case ProfitLossScopeYear:
		if f.Year < 1 {
			return DateRange{}, EntryValidationErrors{{Field: "year", Message: "is required"}}
		}
		from := time.Date(f.Year, 1, 1, 0, 0, 0, 0, time.UTC)
		return DateRange{From: from.Format("2006-01-02"), To: from.AddDate(1, 0, 0).Format("2006-01-02")}, nil
	case ProfitLossScopeGig:
		if f.GigID == nil || *f.GigID == uuid.Nil {
			return DateRange{}, EntryValidationErrors{{Field: "gig_id", Message: "is required"}}
		}
		return DateRange{}, nil
	default:
		return DateRange{}, EntryValidationErrors{{Field: "scope", Message: "must be gig, month, or year"}}
	}
}

var (
	ErrEntryNotFound          = errors.New("finance entry not found")
	ErrEntryConflict          = errors.New("finance entry updated by another writer")
	ErrEntryValidation        = errors.New("invalid finance entry")
	ErrEntryImmutable         = errors.New("auto-generated finance entry is immutable")
	ErrEntryInactive          = errors.New("voided finance entry is immutable")
	ErrGeneratedEntryConflict = errors.New("generated finance entry retry does not match existing entry")
	// A report that cannot be represented exactly by JSON Number clients is
	// a rejected report request, not a partial/truncated result. Reuse the
	// existing 400 validation_failed wire contract while retaining a typed
	// repository error for errors.Is callers.
	ErrEntryAggregateOverflow = fmt.Errorf("%w: finance aggregate exceeds JSON safe integer range", ErrEntryValidation)
)

// These are representation bounds, not business/currency-specific caps.
// All amounts and totals in the current wire format are JSON numbers.
const MaxEntryAmountMinor int64 = 9_007_199_254_740_991 // Number.MAX_SAFE_INTEGER
const MaxSummaryAggregateMinor int64 = MaxEntryAmountMinor

type EntryFieldError struct{ Field, Message string }

func (e EntryFieldError) Error() string { return e.Field + ": " + e.Message }

type EntryValidationErrors []EntryFieldError

func (es EntryValidationErrors) Error() string {
	parts := make([]string, len(es))
	for i, e := range es {
		parts[i] = e.Error()
	}
	return "validation failed: " + strings.Join(parts, "; ")
}
func (es EntryValidationErrors) Is(target error) bool { return target == ErrEntryValidation }
func (es EntryValidationErrors) Unwrap() error        { return ErrEntryValidation }

func ValidateCreateEntry(req CreateEntryRequest) error {
	err := validateEntryFields(req.Kind, req.AmountMinor, req.Currency, req.Category, req.EntryDate, req.Description, req.Notes)
	return validateOptionalGigID(err, req.GigID)
}

func ValidateUpdateEntry(req UpdateEntryRequest) error {
	err := validateEntryFields(req.Kind, req.AmountMinor, req.Currency, req.Category, req.EntryDate, req.Description, req.Notes)
	err = validateOptionalGigID(err, req.GigID)
	if req.UpdatedAt.IsZero() {
		return appendEntryError(err, EntryFieldError{Field: "updated_at", Message: "is required"})
	}
	return err
}

func ValidateGeneratedEntry(req GeneratedEntryInput) error {
	err := validateEntryFields(req.Kind, req.AmountMinor, req.Currency, req.Category, req.EntryDate, req.Description, req.Notes)
	err = validateOptionalGigID(err, req.GigID)
	var errs EntryValidationErrors
	if err != nil {
		errors.As(err, &errs)
	}
	if req.SourceKind != EntrySourceGigPayment && req.SourceKind != EntrySourceInvoicePayment {
		errs = append(errs, EntryFieldError{"source_kind", "must be gig_payment or invoice_payment"})
	}
	if req.SourceID == uuid.Nil {
		errs = append(errs, EntryFieldError{"source_id", "is required"})
	}
	if req.SourceAmountMinor != nil && (*req.SourceAmountMinor <= 0 || *req.SourceAmountMinor > MaxEntryAmountMinor) {
		errs = append(errs, EntryFieldError{"source_amount_minor", "must be positive and within JSON safe integer range"})
	}
	if req.SourceCurrency != nil && !isCurrencyCode(*req.SourceCurrency) {
		errs = append(errs, EntryFieldError{"source_currency", "must be an uppercase 3-letter code"})
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

func validateEntryFields(kind EntryKind, amount int64, currency, category, date, description, notes string) error {
	var errs EntryValidationErrors
	if !kind.IsValid() {
		errs = append(errs, EntryFieldError{"kind", "must be income or expense"})
	}
	if amount <= 0 {
		errs = append(errs, EntryFieldError{"amount_minor", "must be greater than zero"})
	} else if amount > MaxEntryAmountMinor {
		// Preserve exact integer JSON amounts for Number-based clients.
		errs = append(errs, EntryFieldError{"amount_minor", "must be at or below " + strconv.FormatInt(MaxEntryAmountMinor, 10) + " minor units"})
	}
	if !isCurrencyCode(currency) {
		errs = append(errs, EntryFieldError{"currency", "must be an uppercase 3-letter code"})
	}
	if _, err := parseEntryDate(date); err != nil {
		errs = append(errs, EntryFieldError{"entry_date", "must be YYYY-MM-DD"})
	}
	if strings.TrimSpace(category) == "" {
		errs = append(errs, EntryFieldError{"category", "is required"})
	}
	if kind == EntryKindIncome {
		if strings.TrimSpace(description) == "" {
			errs = append(errs, EntryFieldError{"description", "is required for income"})
		}
	} else if kind == EntryKindExpense {
		if strings.TrimSpace(notes) == "" {
			errs = append(errs, EntryFieldError{"notes", "is required for expense"})
		}
	}
	if len(errs) > 0 {
		return errs
	}
	return nil
}

func isCurrencyCode(value string) bool {
	if len(value) != 3 {
		return false
	}
	for i := 0; i < len(value); i++ {
		if value[i] < 'A' || value[i] > 'Z' {
			return false
		}
	}
	return true
}

func appendEntryError(err error, field EntryFieldError) error {
	var errs EntryValidationErrors
	if err != nil && !errors.As(err, &errs) {
		return fmt.Errorf("%w: %v", ErrEntryValidation, err)
	}
	errs = append(errs, field)
	return errs
}

func validateOptionalGigID(err error, gigID *uuid.UUID) error {
	if gigID != nil && *gigID == uuid.Nil {
		return appendEntryError(err, EntryFieldError{Field: "gig_id", Message: "must not be nil UUID"})
	}
	return err
}

func parseEntryDate(value string) (time.Time, error) { return time.Parse("2006-01-02", value) }
