package finance

import (
	"context"
	"errors"
	"strings"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/klubhub/dj/api/internal/gig"
	"github.com/shopspring/decimal"
)

// ReconciliationReason is the reason a finance_entry_reconciliations row was
// raised. Surfaced back to clients so the UI can render the right prompt.
type ReconciliationReason string

const (
	ReconciliationReasonFeeChanged      ReconciliationReason = "fee_changed"
	ReconciliationReasonCurrencyChanged ReconciliationReason = "currency_changed"
	ReconciliationReasonPaymentReversed ReconciliationReason = "payment_reversed"
)

// ReconciliationAction is the user-visible choice attached to a decision.
type ReconciliationAction string

const (
	ReconciliationActionUpdate ReconciliationAction = "update"
	ReconciliationActionDelete ReconciliationAction = "delete"
	ReconciliationActionVoid   ReconciliationAction = "void"
	ReconciliationActionKeep   ReconciliationAction = "keep"
)

// ReconciliationStatus is the lifecycle of a finance_entry_reconciliations
// row.
type ReconciliationStatus string

const (
	ReconciliationStatusPending  ReconciliationStatus = "pending"
	ReconciliationStatusResolved ReconciliationStatus = "resolved"
)

// EntryReconciliation is the durable decision for one (gig, finance entry)
// snapshot, created by the transition processor and resolved by the UI.
type EntryReconciliation struct {
	ID               uuid.UUID              `json:"id"`
	GigID            uuid.UUID              `json:"gig_id"`
	EntryID          uuid.UUID              `json:"entry_id"`
	Reason           ReconciliationReason   `json:"reason"`
	AllowedActions   []ReconciliationAction `json:"allowed_actions"`
	GigAmountMinor   int64                  `json:"gig_amount_minor"`
	GigCurrency      string                 `json:"gig_currency"`
	GigPaymentStatus gig.PaymentStatus      `json:"gig_payment_status"`
	EntryUpdatedAt   time.Time              `json:"entry_updated_at"`
	Status           ReconciliationStatus   `json:"status"`
	Resolution       ReconciliationAction   `json:"resolution,omitempty"`
	CreatedAt        time.Time              `json:"created_at"`
	UpdatedAt        time.Time              `json:"updated_at"`
	ResolvedAt       *time.Time             `json:"resolved_at,omitempty"`
}

// ResolveReconciliationRequest is the body of POST /reconciliations/{id}/resolve.
type ResolveReconciliationRequest struct {
	Action    ReconciliationAction `json:"action"`
	UpdatedAt time.Time            `json:"updated_at"`
}

// FinanceEntryColumns is the projection used for the active-generated-entry
// lookup and the freshly-created row.
const financeEntryColumns = `id, kind, amount_minor, currency, category, entry_date::text, description, notes,
gig_id, status, auto_generated, source_kind, source_id, source_amount_minor, source_currency,
source_description, created_at, updated_at, deleted_at`

func scanFinanceEntry(e *Entry) []any {
	return []any{&e.ID, &e.Kind, &e.AmountMinor, &e.Currency, &e.Category, &e.EntryDate,
		&e.Description, &e.Notes, &e.GigID, &e.Status, &e.AutoGenerated, &e.SourceKind,
		&e.SourceID, &e.SourceAmountMinor, &e.SourceCurrency, &e.SourceDescription,
		&e.CreatedAt, &e.UpdatedAt, &e.DeletedAt}
}

// reconciliationColumns is the projection used to read a pending row back
// out of the database. The COALESCE keeps the row scannable while the
// resolution column is still NULL.
const reconciliationColumns = `id, gig_id, entry_id, reason, allowed_actions, gig_amount_minor,
gig_currency, gig_payment_status, entry_updated_at, status, COALESCE(resolution,''),
created_at, updated_at, resolved_at`

func scanReconciliation(r *EntryReconciliation) []any {
	return []any{&r.ID, &r.GigID, &r.EntryID, &r.Reason, &r.AllowedActions, &r.GigAmountMinor,
		&r.GigCurrency, &r.GigPaymentStatus, &r.EntryUpdatedAt, &r.Status, &r.Resolution,
		&r.CreatedAt, &r.UpdatedAt, &r.ResolvedAt}
}

// Sentinel errors exposed to the API layer.
var (
	ErrReconciliationNotFound = errors.New("finance entry reconciliation not found")
	ErrReconciliationConflict = errors.New("finance entry reconciliation changed; refresh and retry")
	ErrReconciliationAction   = errors.New("reconciliation action is not allowed")
)

// GigPaymentTransitionProcessor is the shared finance implementation wired
// into both the gig repository's UpdateWithPaymentTransition path and the
// invoice-payment sync path. Running both writes through a single processor
// is what guarantees one active generated income row per gig: idempotency
// is enforced by (source_kind, source_id, kind) plus the matching
// reconciliation row.
type GigPaymentTransitionProcessor struct {
	pool *pgxpool.Pool
}

// NewGigPaymentTransitionProcessor returns a processor backed by pool.
func NewGigPaymentTransitionProcessor(pool *pgxpool.Pool) *GigPaymentTransitionProcessor {
	return &GigPaymentTransitionProcessor{pool: pool}
}

// ProcessGigPaymentTransition is the contract declared in
// gig.PaymentTransitionProcessor. When db is nil the processor runs in its
// own transaction so callers like invoice-payment sync can opt out of
// sharing the parent write's tx.
func (p *GigPaymentTransitionProcessor) ProcessGigPaymentTransition(ctx context.Context, db gig.PaymentTransitionTx, before, after gig.PaymentSnapshot) (*gig.PaymentReconciliationMetadata, error) {
	if db != nil {
		return p.process(ctx, db, before, after)
	}
	var metadata *gig.PaymentReconciliationMetadata
	err := pgx.BeginTxFunc(ctx, p.pool, pgx.TxOptions{}, func(tx pgx.Tx) error {
		var inner error
		metadata, inner = p.process(ctx, tx, before, after)
		return inner
	})
	return metadata, err
}

func (p *GigPaymentTransitionProcessor) process(ctx context.Context, db gig.PaymentTransitionTx, before, after gig.PaymentSnapshot) (*gig.PaymentReconciliationMetadata, error) {
	entry, err := getActiveGeneratedGigIncome(ctx, db, after.GigID)
	if err != nil && !errors.Is(err, ErrEntryNotFound) {
		return nil, err
	}
	becamePaid := before.PaymentStatus != gig.PaymentStatusPaid && after.PaymentStatus == gig.PaymentStatusPaid
	leftPaid := before.PaymentStatus == gig.PaymentStatusPaid && after.PaymentStatus != gig.PaymentStatusPaid

	// Nothing for this processor to do: no generated entry exists yet, and
	// this write isn't the one that would create one. Most gig writes (a
	// venue edit, a notes change, a zero-fee gig) take this path — don't
	// validate a fee that isn't being turned into money.
	if entry == nil && !becamePaid {
		return nil, nil
	}

	currency := strings.ToUpper(after.FeeCurrency)
	amountMinor, err := gigFeeToMinor(after.FeeAmount, currency)
	if err != nil {
		if entry == nil {
			// A zero/invalid fee can't fund the first income row; nothing to
			// reconcile against yet, so this isn't a failure of the write.
			return nil, nil
		}
		return nil, err
	}
	if !isCurrencyCode(currency) {
		return nil, EntryValidationErrors{{Field: "fee_currency", Message: "must be an uppercase 3-letter code"}}
	}

	if becamePaid && (entry == nil || errors.Is(err, ErrEntryNotFound)) {
		if _, err := createGeneratedGigIncome(ctx, db, after, amountMinor, currency); err != nil {
			return nil, err
		}
		// Any pending prompt for this gig is now stale: the gig's fee at
		// the moment of paid transition became the entry's source. Mark
		// it acknowledged so the same prompt does not recur.
		if err := resolvePendingAsAcknowledged(ctx, db, after.GigID); err != nil {
			return nil, err
		}
		return nil, nil
	}
	if entry == nil {
		return nil, nil
	}

	var reason ReconciliationReason
	switch {
	case leftPaid:
		reason = ReconciliationReasonPaymentReversed
	case entry.SourceCurrency != nil && *entry.SourceCurrency != currency:
		reason = ReconciliationReasonCurrencyChanged
	case entry.SourceAmountMinor != nil && *entry.SourceAmountMinor != amountMinor:
		reason = ReconciliationReasonFeeChanged
	default:
		if after.PaymentStatus != gig.PaymentStatusPaid {
			// A payment_reversed decision may still be pending from an
			// earlier save (the gig left "paid" on that write, this one
			// doesn't touch fee/currency/status again) — leave it for the
			// user instead of silently acknowledging it here.
			return nil, nil
		}
		// Nothing changed about the snapshot the user was originally
		// prompted for; just refresh the acknowledged state.
		if err := resolvePendingAsAcknowledged(ctx, db, after.GigID); err != nil {
			return nil, err
		}
		return nil, nil
	}

	decision, err := upsertPendingReconciliation(ctx, db, entry, after, amountMinor, currency, reason)
	if err != nil {
		return nil, err
	}
	actions := make([]string, len(decision.AllowedActions))
	for i, action := range decision.AllowedActions {
		actions[i] = string(action)
	}
	return &gig.PaymentReconciliationMetadata{
		ID:             decision.ID,
		EntryID:        decision.EntryID,
		Reason:         string(decision.Reason),
		AllowedActions: actions,
		UpdatedAt:      decision.UpdatedAt,
	}, nil
}

// ErrGigFeeMinorUnitPrecision is returned when a gig fee carries more
// fractional digits than its currency's minor unit allows, since finance
// stores money in integer minor units.
var ErrGigFeeMinorUnitPrecision = errors.New("gig fee has more decimal places than its currency allows")

// zeroDecimalCurrencies and threeDecimalCurrencies are ISO 4217 exceptions
// to the usual 2-digit minor unit, mirroring what the frontend gets from
// Intl.NumberFormat(...).resolvedOptions().maximumFractionDigits
// (apps/dj/app/utils/money.ts currencyDigits) — a Go equivalent, since
// there is no Intl here.
var zeroDecimalCurrencies = map[string]bool{
	"BIF": true, "CLP": true, "DJF": true, "GNF": true, "ISK": true, "JPY": true,
	"KMF": true, "KRW": true, "PYG": true, "RWF": true, "UGX": true, "VND": true,
	"VUV": true, "XAF": true, "XOF": true, "XPF": true,
}

var threeDecimalCurrencies = map[string]bool{
	"BHD": true, "IQD": true, "JOD": true, "KWD": true, "LYD": true, "OMR": true, "TND": true,
}

// currencyMinorDigits returns how many fractional digits currency's minor
// unit has (JPY 0, BHD 3, everything else 2 — the common case).
func currencyMinorDigits(currency string) int {
	switch {
	case zeroDecimalCurrencies[currency]:
		return 0
	case threeDecimalCurrencies[currency]:
		return 3
	default:
		return 2
	}
}

// gigFeeToMinor converts a gig fee (decimal major units) into integer
// minor units, scaled by currency's own minor-unit exponent rather than
// always by 100 — a flat ×100 overstates a JPY fee 100×. We accept up to
// that many fractional digits and reject anything finer so we never
// silently truncate user money.
func gigFeeToMinor(value decimal.Decimal, currency string) (int64, error) {
	if !value.IsPositive() {
		return 0, ErrGigFeeMinorUnitPrecision
	}
	digits := int32(currencyMinorDigits(currency))
	scale := decimal.New(1, digits)
	scaled := value.Mul(scale)
	// The gig table stores fee_amount as DECIMAL(12,2), so a value read
	// back from Postgres always carries exponent -2 (e.g. JPY 500 comes
	// back as "500.00"), regardless of what the currency actually allows —
	// checking Exponent() directly would reject every non-2-decimal
	// currency read from the DB. Checking whether the *scaled* value is a
	// whole number instead catches real over-precision (e.g. ¥500.50)
	// without being fooled by DB zero-padding.
	if !scaled.IsInteger() {
		return 0, ErrGigFeeMinorUnitPrecision
	}
	return scaled.BigInt().Int64(), nil
}

// getActiveGeneratedGigIncome returns the single active auto-generated
// income row linked to gigID, or ErrEntryNotFound. The unique partial
// index on (source_kind, source_id, kind) where auto_generated=true and
// status='active' guarantees at most one row.
func getActiveGeneratedGigIncome(ctx context.Context, db gig.PaymentTransitionTx, gigID uuid.UUID) (*Entry, error) {
	var e Entry
	err := db.QueryRow(ctx, `SELECT `+financeEntryColumns+` FROM finance_entries
		WHERE auto_generated=true AND status='active' AND deleted_at IS NULL AND gig_id=$1
		ORDER BY created_at DESC LIMIT 1`, gigID).Scan(scanFinanceEntry(&e)...)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrEntryNotFound
	}
	if err != nil {
		return nil, err
	}
	return &e, nil
}

// createGeneratedGigIncome idempotently inserts the auto-generated
// income row. The (source_kind, source_id, kind) partial unique index
// guarantees at most one active row per gig. On a conflict we look the
// existing row up and return it when the payload matches (idempotent
// retry); otherwise we surface ErrGeneratedEntryConflict so the caller
// can decide whether to update the existing row via the reconciliation
// flow or void it.
func createGeneratedGigIncome(ctx context.Context, db gig.PaymentTransitionTx, snap gig.PaymentSnapshot, amountMinor int64, currency string) (*Entry, error) {
	if amountMinor <= 0 || amountMinor > MaxEntryAmountMinor {
		return nil, EntryValidationErrors{{Field: "amount_minor", Message: "must be positive and within JSON safe integer range"}}
	}
	date := snap.Date.Format("2006-01-02")
	description := gigLineDescription(snap.EventName, snap.Venue, "", date)
	gigID := snap.GigID
	sourceDesc := "gig:" + gigID.String()
	sourceAmount := amountMinor
	sourceCurrency := currency
	input := GeneratedEntryInput{Kind: EntryKindIncome, AmountMinor: amountMinor, Currency: currency,
		Category: "gig_fee", EntryDate: date, Description: description, GigID: &gigID,
		SourceKind: EntrySourceGigPayment, SourceID: gigID, SourceAmountMinor: &sourceAmount,
		SourceCurrency: &sourceCurrency, SourceDescription: sourceDesc}

	// Probe first. The (source_kind, source_id, kind) partial unique
	// index only covers active, not-deleted rows; an existing voided
	// or deleted row would otherwise let this INSERT silently create a
	// fresh active replacement. An existing active row with a
	// matching payload is reused (idempotent replay); an active row
	// with a mismatched payload is a hard conflict (same source, new
	// numbers — must go through the reconciliation flow).
	var existing Entry
	err := db.QueryRow(ctx, `SELECT `+financeEntryColumns+` FROM finance_entries
		WHERE auto_generated=true AND source_kind='gig_payment' AND source_id=$1 AND kind='income'
		  AND deleted_at IS NULL
		ORDER BY created_at DESC LIMIT 1`, gigID).Scan(scanFinanceEntry(&existing)...)
	if err == nil {
		if existing.Status == EntryStatusActive && existing.DeletedAt == nil {
			if !sameGeneratedIdentity(&existing, input) {
				return nil, ErrGeneratedEntryConflict
			}
			return &existing, nil
		}
		// Voided/deleted prior row: the gig has been re-paid; INSERT a
		// fresh active row to replace it.
	} else if !errors.Is(err, pgx.ErrNoRows) {
		return nil, err
	}

	var e Entry
	err = db.QueryRow(ctx, `INSERT INTO finance_entries
		(kind, amount_minor, currency, category, entry_date, description, notes, gig_id,
		 auto_generated, source_kind, source_id, source_amount_minor, source_currency, source_description)
		VALUES ('income', $1, $2, 'gig_fee', $3::date, $4, '', $5,
		 true, 'gig_payment', $6, $7, $8, $9)
		ON CONFLICT (source_kind, source_id, kind)
		  WHERE auto_generated=true AND source_id IS NOT NULL AND status='active' AND deleted_at IS NULL
		DO NOTHING
		RETURNING `+financeEntryColumns,
		amountMinor, currency, date, description, gigID,
		gigID, sourceAmount, sourceCurrency, sourceDesc).Scan(scanFinanceEntry(&e)...)
	if err == nil {
		return &e, nil
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		if isEntryGigFKViolation(err) {
			return nil, EntryValidationErrors{{Field: "gig_id", Message: "does not reference an existing gig"}}
		}
		return nil, err
	}
	// ON CONFLICT waited for the concurrent winner without aborting this
	// transaction. A separate READ COMMITTED statement sees that row.
	err = db.QueryRow(ctx, `SELECT `+financeEntryColumns+` FROM finance_entries
		WHERE auto_generated=true AND source_kind='gig_payment' AND source_id=$1 AND kind='income'
		  AND status='active' AND deleted_at IS NULL`,
		gigID).Scan(scanFinanceEntry(&existing)...)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, ErrGeneratedEntryConflict
	}
	if err != nil {
		return nil, err
	}
	if !sameGeneratedIdentity(&existing, input) {
		return nil, ErrGeneratedEntryConflict
	}
	return &existing, nil
}

// resolvePendingAsAcknowledged transitions every pending reconciliation
// row for gigID to resolved with no resolution code. This is used after a
// paid transition or when the snapshot the prompt was raised against no
// longer differs from the current gig — the user effectively answered by
// doing nothing (the entry already matches).
func resolvePendingAsAcknowledged(ctx context.Context, db gig.PaymentTransitionTx, gigID uuid.UUID) error {
	_, err := db.Exec(ctx, `UPDATE finance_entry_reconciliations
		SET status='resolved', resolution='keep', resolved_at=clock_timestamp(), updated_at=clock_timestamp()
		WHERE gig_id=$1 AND status='pending'`, gigID)
	if err != nil {
		return err
	}
	return nil
}

// upsertPendingReconciliation creates one pending decision per gig (the
// partial unique index guarantees that) or refreshes the existing one
// with the latest snapshot so the UI sees the most recent fee/currency.
func upsertPendingReconciliation(ctx context.Context, db gig.PaymentTransitionTx, entry *Entry, snap gig.PaymentSnapshot, amountMinor int64, currency string, reason ReconciliationReason) (*EntryReconciliation, error) {
	actions := allowedActionsFor(reason)
	var out EntryReconciliation
	err := db.QueryRow(ctx, `INSERT INTO finance_entry_reconciliations
		(gig_id, entry_id, reason, allowed_actions, gig_amount_minor, gig_currency, gig_payment_status, entry_updated_at, status)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'pending')
		ON CONFLICT (gig_id) WHERE status='pending'
		DO UPDATE SET
		  reason = EXCLUDED.reason,
		  allowed_actions = EXCLUDED.allowed_actions,
		  gig_amount_minor = EXCLUDED.gig_amount_minor,
		  gig_currency = EXCLUDED.gig_currency,
		  gig_payment_status = EXCLUDED.gig_payment_status,
		  entry_updated_at = EXCLUDED.entry_updated_at,
		  updated_at = clock_timestamp()
		RETURNING `+reconciliationColumns,
		snap.GigID, entry.ID, reason, actions, amountMinor, currency, snap.PaymentStatus, entry.UpdatedAt,
	).Scan(scanReconciliation(&out)...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// allowedActionsFor enforces the action/reason pair documented in the
// migration's allowed_actions CHECK constraint.
func allowedActionsFor(reason ReconciliationReason) []ReconciliationAction {
	switch reason {
	case ReconciliationReasonFeeChanged, ReconciliationReasonCurrencyChanged:
		return []ReconciliationAction{ReconciliationActionUpdate, ReconciliationActionKeep}
	case ReconciliationReasonPaymentReversed:
		return []ReconciliationAction{ReconciliationActionDelete, ReconciliationActionVoid, ReconciliationActionKeep}
	}
	return nil
}
