package finance

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/klubhub/dj/api/internal/gig"
	"github.com/shopspring/decimal"
)

func resetGigPaymentReconciliationState(t *testing.T) {
	t.Helper()
	requirePG(t)
	ctx := context.Background()
	_, _ = testPool.Exec(ctx, `DELETE FROM finance_entry_reconciliations`)
	_, _ = testPool.Exec(ctx, `DELETE FROM finance_entries`)
	// Drop the billing profile too so the FIN tests cannot leave a
	// seeded profile behind for tests that follow in the package
	// (e.g. TestIntegration_GetSeedsEmptyRow expects a clean slate).
	_, _ = testPool.Exec(ctx, `DELETE FROM billing_profiles`)
}

func createTransitionGig(t *testing.T, processor gig.PaymentTransitionProcessor, fee, currency string) (*gig.Service, *gig.Gig) {
	t.Helper()
	amount, err := decimal.NewFromString(fee)
	if err != nil {
		t.Fatal(err)
	}
	repo := gig.NewRepository(testPool)
	svc := gig.NewServiceWithPaymentTransitionProcessor(repo, nil, nil, nil, nil, processor)
	created, err := svc.CreateGig(context.Background(), &gig.GigCreate{
		Date: time.Date(2026, 9, 27, 20, 0, 0, 0, time.UTC), Venue: "Berghain", City: "Berlin",
		EventName: "Sunday Session", FeeAmount: amount, FeeCurrency: currency,
	})
	if err != nil {
		t.Fatalf("create gig: %v", err)
	}
	return svc, created
}

func updateTransitionGig(t *testing.T, svc *gig.Service, current *gig.Gig, mutate func(*gig.GigUpdate)) *gig.Gig {
	t.Helper()
	req := &gig.GigUpdate{UpdatedAt: current.UpdatedAt}
	mutate(req)
	updated, err := svc.UpdateGig(context.Background(), current.ID, req)
	if err != nil {
		t.Fatalf("update gig: %v", err)
	}
	return updated
}

func activeGeneratedIncome(t *testing.T, gigID uuid.UUID) *Entry {
	t.Helper()
	var id uuid.UUID
	if err := testPool.QueryRow(context.Background(), `
		SELECT id FROM finance_entries
		WHERE gig_id=$1 AND kind='income' AND auto_generated=true
		  AND status='active' AND deleted_at IS NULL`, gigID).Scan(&id); err != nil {
		t.Fatalf("active generated income: %v", err)
	}
	e, err := NewEntryRepository(testPool).GetIncludingInactive(context.Background(), id)
	if err != nil {
		t.Fatal(err)
	}
	return e
}

func generatedIncomeCount(t *testing.T, gigID uuid.UUID, activeOnly bool) int {
	t.Helper()
	q := `SELECT count(*) FROM finance_entries WHERE gig_id=$1 AND kind='income' AND auto_generated=true`
	if activeOnly {
		q += ` AND status='active' AND deleted_at IS NULL`
	}
	var count int
	if err := testPool.QueryRow(context.Background(), q, gigID).Scan(&count); err != nil {
		t.Fatal(err)
	}
	return count
}

func TestIntegration_FIN03ManualPaidTransitionCreatesOneIncomeAndReplaysIdempotently(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	ctx := context.Background()
	processor := NewGigPaymentTransitionProcessor(testPool)
	svc, created := createTransitionGig(t, processor, "123.45", "EUR")
	paid := gig.PaymentStatusPaid
	updated := updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })

	entry := activeGeneratedIncome(t, created.ID)
	if entry.AmountMinor != 12345 || entry.Currency != "EUR" || entry.Category != "gig_fee" || !entry.AutoGenerated ||
		entry.SourceKind != EntrySourceGigPayment || entry.SourceID == nil || *entry.SourceID != created.ID || entry.EntryDate != "2026-09-27" {
		t.Fatalf("generated entry = %+v", entry)
	}
	if updated.FinanceReconciliation != nil {
		t.Fatalf("initial paid transition must not require reconciliation: %+v", updated.FinanceReconciliation)
	}

	// A replayed paid write and direct processor replay both preserve the same active row.
	updated = updateTransitionGig(t, svc, updated, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
	if _, err := processor.ProcessGigPaymentTransition(ctx, nil, gig.PaymentSnapshotFromGig(updated), gig.PaymentSnapshotFromGig(updated)); err != nil {
		t.Fatalf("processor replay: %v", err)
	}
	if got := generatedIncomeCount(t, created.ID, true); got != 1 {
		t.Fatalf("active generated income count = %d, want 1", got)
	}
}

func TestIntegration_FIN04FeeAndCurrencyChangesPersistDecisionWithoutSilentMutation(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	ctx := context.Background()
	processor := NewGigPaymentTransitionProcessor(testPool)
	svc, created := createTransitionGig(t, processor, "250.00", "EUR")
	paid := gig.PaymentStatusPaid
	paidGig := updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
	original := activeGeneratedIncome(t, created.ID)

	fee := decimal.RequireFromString("275.55")
	changed := updateTransitionGig(t, svc, paidGig, func(u *gig.GigUpdate) { u.FeeAmount = &fee })
	if changed.FinanceReconciliation == nil || changed.FinanceReconciliation.Reason != string(ReconciliationReasonFeeChanged) {
		t.Fatalf("gig update decision = %+v", changed.FinanceReconciliation)
	}
	preserved := activeGeneratedIncome(t, created.ID)
	if preserved.AmountMinor != original.AmountMinor || preserved.Currency != original.Currency {
		t.Fatalf("fee change silently mutated entry: before=%+v after=%+v", original, preserved)
	}
	decision, err := NewEntryService(NewEntryRepository(testPool)).GetPendingReconciliationByGig(ctx, created.ID)
	if err != nil || decision.Reason != ReconciliationReasonFeeChanged || len(decision.AllowedActions) != 2 {
		t.Fatalf("pending fee decision = %+v err=%v", decision, err)
	}

	currency := "USD"
	changed = updateTransitionGig(t, svc, changed, func(u *gig.GigUpdate) { u.FeeCurrency = &currency })
	decision, err = NewEntryService(NewEntryRepository(testPool)).GetPendingReconciliationByEntry(ctx, original.ID)
	if err != nil || decision.Reason != ReconciliationReasonCurrencyChanged || decision.GigCurrency != "USD" || decision.GigAmountMinor != 27555 {
		t.Fatalf("pending currency decision = %+v err=%v", decision, err)
	}
	if changed.FinanceReconciliation == nil || changed.FinanceReconciliation.ID != decision.ID {
		t.Fatalf("response metadata = %+v decision=%+v", changed.FinanceReconciliation, decision)
	}
}

func TestIntegration_FIN05ReversalResolutionActionsAndPaidAgainRule(t *testing.T) {
	for _, action := range []ReconciliationAction{ReconciliationActionKeep, ReconciliationActionVoid, ReconciliationActionDelete} {
		t.Run(string(action), func(t *testing.T) {
			resetGigPaymentReconciliationState(t)
			ctx := context.Background()
			processor := NewGigPaymentTransitionProcessor(testPool)
			svc, created := createTransitionGig(t, processor, "99.99", "GBP")
			paid := gig.PaymentStatusPaid
			paidGig := updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
			original := activeGeneratedIncome(t, created.ID)
			unpaid := gig.PaymentStatusUnpaid
			reverted := updateTransitionGig(t, svc, paidGig, func(u *gig.GigUpdate) { u.PaymentStatus = &unpaid })
			if reverted.FinanceReconciliation == nil || reverted.FinanceReconciliation.Reason != string(ReconciliationReasonPaymentReversed) {
				t.Fatalf("reversal metadata = %+v", reverted.FinanceReconciliation)
			}
			decision, err := NewEntryService(NewEntryRepository(testPool)).GetPendingReconciliationByGig(ctx, created.ID)
			if err != nil || decision.EntryID != original.ID || decision.Reason != ReconciliationReasonPaymentReversed {
				t.Fatalf("pending reversal = %+v err=%v", decision, err)
			}
			resolved, err := NewEntryService(NewEntryRepository(testPool)).ResolveReconciliation(ctx, decision.ID, ResolveReconciliationRequest{
				Action: action, UpdatedAt: decision.UpdatedAt,
			})
			if err != nil || resolved.Status != ReconciliationStatusResolved || resolved.Resolution != action {
				t.Fatalf("resolve %s = %+v err=%v", action, resolved, err)
			}
			if _, err := NewEntryService(NewEntryRepository(testPool)).GetPendingReconciliationByGig(ctx, created.ID); !errors.Is(err, ErrReconciliationNotFound) {
				t.Fatalf("resolved decision still pending: %v", err)
			}

			paidAgain := updateTransitionGig(t, svc, reverted, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
			active := activeGeneratedIncome(t, created.ID)
			if action == ReconciliationActionKeep {
				if active.ID != original.ID || generatedIncomeCount(t, created.ID, false) != 1 {
					t.Fatalf("keep must reuse active row: original=%s active=%s total=%d", original.ID, active.ID, generatedIncomeCount(t, created.ID, false))
				}
			} else {
				if active.ID == original.ID || generatedIncomeCount(t, created.ID, false) != 2 {
					t.Fatalf("%s must create one replacement row: original=%s active=%s total=%d", action, original.ID, active.ID, generatedIncomeCount(t, created.ID, false))
				}
			}
			if generatedIncomeCount(t, created.ID, true) != 1 || paidAgain.FinanceReconciliation != nil {
				t.Fatalf("paid again state: active=%d metadata=%+v", generatedIncomeCount(t, created.ID, true), paidAgain.FinanceReconciliation)
			}
		})
	}
}

func TestIntegration_ReconciliationUpdateKeepRefreshAndStaleConflict(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	ctx := context.Background()
	processor := NewGigPaymentTransitionProcessor(testPool)
	svc, created := createTransitionGig(t, processor, "50.00", "EUR")
	paid := gig.PaymentStatusPaid
	current := updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
	fee := decimal.RequireFromString("60.25")
	current = updateTransitionGig(t, svc, current, func(u *gig.GigUpdate) { u.FeeAmount = &fee })
	entrySvc := NewEntryService(NewEntryRepository(testPool))
	decision, err := entrySvc.GetPendingReconciliationByGig(ctx, created.ID)
	if err != nil {
		t.Fatal(err)
	}
	stale := decision.UpdatedAt.Add(-time.Nanosecond)
	if _, err := entrySvc.ResolveReconciliation(ctx, decision.ID, ResolveReconciliationRequest{Action: ReconciliationActionUpdate, UpdatedAt: stale}); !errors.Is(err, ErrReconciliationConflict) {
		t.Fatalf("stale resolution error = %v", err)
	}
	resolved, err := entrySvc.ResolveReconciliation(ctx, decision.ID, ResolveReconciliationRequest{Action: ReconciliationActionUpdate, UpdatedAt: decision.UpdatedAt})
	if err != nil || resolved.Resolution != ReconciliationActionUpdate {
		t.Fatalf("update resolution = %+v err=%v", resolved, err)
	}
	entry := activeGeneratedIncome(t, created.ID)
	if entry.AmountMinor != 6025 || entry.Currency != "EUR" {
		t.Fatalf("updated entry = %+v", entry)
	}

	currency := "CHF"
	current = updateTransitionGig(t, svc, current, func(u *gig.GigUpdate) { u.FeeCurrency = &currency })
	decision, err = entrySvc.GetPendingReconciliationByGig(ctx, created.ID)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := entrySvc.ResolveReconciliation(ctx, decision.ID, ResolveReconciliationRequest{Action: ReconciliationActionKeep, UpdatedAt: decision.UpdatedAt}); err != nil {
		t.Fatal(err)
	}
	entry = activeGeneratedIncome(t, created.ID)
	if entry.AmountMinor != 6025 || entry.Currency != "EUR" || entry.SourceAmountMinor == nil || *entry.SourceAmountMinor != 6025 || entry.SourceCurrency == nil || *entry.SourceCurrency != "CHF" {
		t.Fatalf("keep must preserve entry and acknowledge gig snapshot: %+v", entry)
	}
	// An unrelated paid->paid edit must not recreate the acknowledged prompt.
	venue := "Panorama Bar"
	current = updateTransitionGig(t, svc, current, func(u *gig.GigUpdate) { u.Venue = &venue })
	if current.FinanceReconciliation != nil {
		t.Fatalf("acknowledged prompt recurred: %+v", current.FinanceReconciliation)
	}
}

func TestIntegration_ZeroFeeGigEditDoesNotFail(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	processor := NewGigPaymentTransitionProcessor(testPool)
	// A gig's fee_amount defaults to 0 (migration 005_gigs.sql); every
	// other write to it (a notes edit here) must not run the fee/currency
	// validation the paid-transition path needs — gigFeeToMinor rejects
	// any non-positive amount, and there is no active entry yet to fund.
	svc, created := createTransitionGig(t, processor, "0", "EUR")
	notes := "Load-in at 22:00"
	updated := updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.Notes = &notes })
	if updated.Notes != notes {
		t.Fatalf("notes edit should have saved, got %+v", updated)
	}
	if generatedIncomeCount(t, created.ID, false) != 0 {
		t.Fatalf("a zero-fee, unpaid gig must not generate income")
	}
}

func TestIntegration_UnrelatedEditDoesNotAcknowledgePendingReversal(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	ctx := context.Background()
	processor := NewGigPaymentTransitionProcessor(testPool)
	svc, created := createTransitionGig(t, processor, "99.99", "GBP")
	paid := gig.PaymentStatusPaid
	paidGig := updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
	unpaid := gig.PaymentStatusUnpaid
	reverted := updateTransitionGig(t, svc, paidGig, func(u *gig.GigUpdate) { u.PaymentStatus = &unpaid })
	if reverted.FinanceReconciliation == nil || reverted.FinanceReconciliation.Reason != string(ReconciliationReasonPaymentReversed) {
		t.Fatalf("reversal metadata = %+v", reverted.FinanceReconciliation)
	}

	// An unrelated edit while the gig is still unpaid (fee/currency
	// unchanged, entry still active) must not silently acknowledge the
	// still-pending payment_reversed decision — the user hasn't answered
	// it yet.
	notes := "Rebooked pending refund"
	edited := updateTransitionGig(t, svc, reverted, func(u *gig.GigUpdate) { u.Notes = &notes })
	if edited.FinanceReconciliation != nil {
		t.Fatalf("an unrelated edit must not raise a new decision: %+v", edited.FinanceReconciliation)
	}
	decision, err := NewEntryService(NewEntryRepository(testPool)).GetPendingReconciliationByGig(ctx, created.ID)
	if err != nil || decision.Reason != ReconciliationReasonPaymentReversed || decision.Status != ReconciliationStatusPending {
		t.Fatalf("the payment_reversed decision must still be pending, got %+v err=%v", decision, err)
	}
}

func TestIntegration_JPYFeeUsesZeroDecimalMinorUnits(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	processor := NewGigPaymentTransitionProcessor(testPool)
	// JPY has no minor unit: ¥50,000 is 50000 minor units, not 5,000,000.
	svc, created := createTransitionGig(t, processor, "50000", "JPY")
	paid := gig.PaymentStatusPaid
	updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
	entry := activeGeneratedIncome(t, created.ID)
	if entry.AmountMinor != 50000 || entry.Currency != "JPY" {
		t.Fatalf("JPY entry = %+v, want amount_minor=50000", entry)
	}
}

func TestIntegration_InvoicePaymentSyncUsesSameTransitionProcessorWithoutDuplicates(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	t.Cleanup(func() {
		// Don't leave billing_profiles seeded — subsequent tests in
		// the package (e.g. TestIntegration_GetSeedsEmptyRow) expect
		// a clean slate so they can assert the seed semantics.
		_, _ = testPool.Exec(context.Background(), `DELETE FROM billing_profiles`)
	})
	ctx := context.Background()
	setBillingProfile(t, nil)
	invoiceSvc := newTestInvoiceService()
	processor := NewGigPaymentTransitionProcessor(testPool)
	paySvc := NewPaymentService(NewPaymentRepositoryWithTransitionProcessor(testPool, processor))
	gigID := insertTestGig(t, "EUR")
	draft := issuableDraft(t, invoiceSvc, gigID, "HOOK", nil)
	issued, err := invoiceSvc.Issue(ctx, draft.ID, IssueInvoiceRequest{UpdatedAt: draft.UpdatedAt})
	if err != nil {
		t.Fatal(err)
	}
	payment, err := paySvc.Create(ctx, issued.ID, CreatePaymentRequest{Currency: "EUR", AmountMinor: issued.NetPayableMinor, Kind: PaymentKindPayment})
	if err != nil {
		t.Fatal(err)
	}
	completed, err := paySvc.Update(ctx, payment.ID, UpdatePaymentRequest{Status: PaymentStatusCompleted, UpdatedAt: payment.UpdatedAt})
	if err != nil {
		t.Fatal(err)
	}
	if entry := activeGeneratedIncome(t, gigID); entry.AmountMinor != 25000 || entry.Currency != "EUR" {
		t.Fatalf("invoice-driven entry = %+v", entry)
	}
	// Replaying completed status goes through sync again but cannot duplicate revenue.
	if _, err := paySvc.Update(ctx, payment.ID, UpdatePaymentRequest{Status: PaymentStatusCompleted, UpdatedAt: completed.UpdatedAt}); err != nil {
		t.Fatal(err)
	}
	if got := generatedIncomeCount(t, gigID, true); got != 1 {
		t.Fatalf("active generated income count = %d, want 1", got)
	}
}

func TestIntegration_TransitionHookFailureRollsBackGigStatus(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	ctx := context.Background()
	processor := failingPaymentTransitionProcessor{err: errors.New("ledger unavailable")}
	svc, created := createTransitionGig(t, processor, "10.00", "EUR")
	paid := gig.PaymentStatusPaid
	_, err := svc.UpdateGig(ctx, created.ID, &gig.GigUpdate{PaymentStatus: &paid, UpdatedAt: created.UpdatedAt})
	if err == nil || !strings.Contains(err.Error(), "ledger unavailable") {
		t.Fatalf("update error = %v", err)
	}
	current, err := svc.GetGig(ctx, created.ID)
	if err != nil {
		t.Fatal(err)
	}
	if current.PaymentStatus != gig.PaymentStatusUnpaid || generatedIncomeCount(t, created.ID, true) != 0 {
		t.Fatalf("failed hook committed partial state: gig=%+v", current)
	}
}

type failingPaymentTransitionProcessor struct{ err error }

func (p failingPaymentTransitionProcessor) ProcessGigPaymentTransition(context.Context, gig.PaymentTransitionTx, gig.PaymentSnapshot, gig.PaymentSnapshot) (*gig.PaymentReconciliationMetadata, error) {
	return nil, p.err
}

func TestIntegration_ReconciliationHTTPGetAndResolve(t *testing.T) {
	resetGigPaymentReconciliationState(t)
	processor := NewGigPaymentTransitionProcessor(testPool)
	svc, created := createTransitionGig(t, processor, "80.00", "EUR")
	paid := gig.PaymentStatusPaid
	current := updateTransitionGig(t, svc, created, func(u *gig.GigUpdate) { u.PaymentStatus = &paid })
	fee := decimal.RequireFromString("90.00")
	_ = updateTransitionGig(t, svc, current, func(u *gig.GigUpdate) { u.FeeAmount = &fee })

	h := NewEntryHandler(NewEntryService(NewEntryRepository(testPool)))
	get := httptest.NewRecorder()
	h.ServeHTTP(get, httptest.NewRequest(http.MethodGet, "/api/v1/finance/reconciliations?gig_id="+created.ID.String(), nil))
	if get.Code != http.StatusOK || !strings.Contains(get.Body.String(), `"reason":"fee_changed"`) {
		t.Fatalf("GET reconciliation: status=%d body=%s", get.Code, get.Body.String())
	}
	decision, err := NewEntryService(NewEntryRepository(testPool)).GetPendingReconciliationByGig(context.Background(), created.ID)
	if err != nil {
		t.Fatal(err)
	}
	body := `{"action":"keep","updated_at":"` + decision.UpdatedAt.Format(time.RFC3339Nano) + `"}`
	resolve := httptest.NewRecorder()
	h.ServeHTTP(resolve, httptest.NewRequest(http.MethodPost, "/api/v1/finance/reconciliations/"+decision.ID.String()+"/resolve", strings.NewReader(body)))
	if resolve.Code != http.StatusOK || !strings.Contains(resolve.Body.String(), `"resolution":"keep"`) {
		t.Fatalf("resolve reconciliation: status=%d body=%s", resolve.Code, resolve.Body.String())
	}
	refresh := httptest.NewRecorder()
	h.ServeHTTP(refresh, httptest.NewRequest(http.MethodGet, "/api/v1/finance/reconciliations?gig_id="+created.ID.String(), nil))
	if refresh.Code != http.StatusNotFound {
		t.Fatalf("resolved refresh status=%d body=%s", refresh.Code, refresh.Body.String())
	}
}
