#!/bin/bash
# =============================================================================
# Generate the NATS JWT credential chain for KlubHub Promoter (plan §13.6).
# Adapted from the Mettal staging script (same author).
#
# nsc keeps private keys in its own keystore (~/.local/share/nats/nsc).
# Written to --out-dir (must be gitignored; the script checks):
#   auth.conf               operator + account JWTs for a MEMORY resolver
#   promoter-api.creds      outbox relay: publish-only on tenant.> / audit.>
#   promoter-bff.creds      Nuxt server (nuxt-nats): consume-only
# The .creds files contain NKey seeds: secrets. For deployments put them in
# Infisical / Docker secrets; never commit them.
#
# Usage: infra/promoter/nats/generate-creds.sh --out-dir .local/promoter/secrets/nats
# =============================================================================
set -euo pipefail

OUT_DIR=""
OPERATOR="klubhub-promoter"
ACCOUNT="PROMOTER"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --out-dir) OUT_DIR="$2"; shift 2 ;;
        --operator) OPERATOR="$2"; shift 2 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done
[[ -n "$OUT_DIR" ]] || { echo "Error: --out-dir is required." >&2; exit 1; }
command -v nsc >/dev/null 2>&1 || { echo "Error: nsc not installed (brew install nsc)." >&2; exit 1; }

mkdir -p "$OUT_DIR"
OUT_DIR_ABS="$(cd "$OUT_DIR" && pwd)"
if REPO_ROOT_DIR="$(git -C "$OUT_DIR_ABS" rev-parse --show-toplevel 2>/dev/null)"; then
    if ! git -C "$REPO_ROOT_DIR" check-ignore -q "$OUT_DIR_ABS"; then
        echo "Error: '$OUT_DIR_ABS' is inside the repo but NOT gitignored. This script writes NKey seeds." >&2
        exit 1
    fi
fi

if ! nsc describe operator "$OPERATOR" >/dev/null 2>&1; then
    nsc add operator --name "$OPERATOR" --sys >/dev/null
fi
# Select explicitly on both paths so users never land under another operator.
nsc env --operator "$OPERATOR" >/dev/null

if ! nsc describe account --name "$ACCOUNT" >/dev/null 2>&1; then
    nsc add account --name "$ACCOUNT" >/dev/null
fi
# JetStream must be enabled on the account, not only on the server.
nsc edit account --name "$ACCOUNT" --js-mem-storage 512M --js-disk-storage 10G >/dev/null

add_user() { # name, then nsc permission flags
    local name="$1"; shift
    if ! nsc describe user --account "$ACCOUNT" --name "$name" >/dev/null 2>&1; then
        nsc add user --account "$ACCOUNT" --name "$name" "$@" >/dev/null
    else
        nsc edit user --account "$ACCOUNT" --name "$name" "$@" >/dev/null
    fi
    nsc generate creds --account "$ACCOUNT" --name "$name" > "$OUT_DIR_ABS/$name.creds"
    chmod 600 "$OUT_DIR_ABS/$name.creds"
}

# Outbox relay: publishes domain and audit events, manages its streams.
add_user promoter-api \
    --allow-pub "tenant.>,audit.>,\$JS.API.>" \
    --allow-sub "_INBOX.>"

# Nuxt server (nuxt-nats ephemeral consumers for SSE): reads, never publishes events.
add_user promoter-bff \
    --allow-pub "\$JS.API.INFO,\$JS.API.STREAM.INFO.PROMOTER_EVENTS,\$JS.API.CONSUMER.>,\$JS.ACK.PROMOTER_EVENTS.>" \
    --allow-sub "_INBOX.>,tenant.>"

OPERATOR_JWT="$(nsc describe operator "$OPERATOR" --raw)"
SYS_JWT="$(nsc describe account --name SYS --raw)"
SYS_PUB="$(nsc describe account --name SYS --field sub | tr -d '"')"
ACCOUNT_JWT="$(nsc describe account --name "$ACCOUNT" --raw)"
ACCOUNT_PUB="$(nsc describe account --name "$ACCOUNT" --field sub | tr -d '"')"

cat > "$OUT_DIR_ABS/auth.conf" <<AUTHCONF
# GENERATED by infra/promoter/nats/generate-creds.sh. Do not hand-edit.
operator: $OPERATOR_JWT
system_account: $SYS_PUB
resolver: MEMORY
resolver_preload: {
  $SYS_PUB: $SYS_JWT
  $ACCOUNT_PUB: $ACCOUNT_JWT
}
AUTHCONF

echo "Wrote auth.conf, promoter-api.creds and promoter-bff.creds to $OUT_DIR_ABS"
