const now = new Date('2026-04-27T13:00:00Z')

function iso(daysFromNow: number, hour = 20, min = 0) {
  const d = new Date(now)
  d.setDate(d.getDate() + daysFromNow)
  d.setUTCHours(hour, min, 0, 0)
  return d.toISOString()
}

const MOCK_POSTS = [
  {
    id: 'sp-001',
    accountId: 'acc-001',
    status: 'scheduled',
    postType: 'feed',
    caption: 'Techno Ritual Vol. 4 — 47 tracks from Cyber Void Berlin. One of the best sets I\'ve played this year. 🖤 #techno #berlin #djset #cybervoid',
    imageMinioPath: 'social/sp-001.jpg',
    scheduledAtUtc: iso(2, 23, 45),
    timezoneName: 'Europe/Berlin',
    retryCount: 0,
    nextRetryAt: null,
    lastError: '',
    createdAt: iso(-1, 10, 0),
    updatedAt: iso(-1, 10, 0),
  },
  {
    id: 'sp-002',
    accountId: 'acc-001',
    status: 'draft',
    postType: 'story',
    caption: 'Closing set highlights from Tresor last weekend.. The Globus never sleeps 🌑 #tresor #techno #closing',
    imageMinioPath: 'social/sp-002.jpg',
    scheduledAtUtc: iso(6, 20, 0),
    timezoneName: 'Europe/Berlin',
    retryCount: 0,
    nextRetryAt: null,
    lastError: '',
    createdAt: iso(-2, 14, 30),
    updatedAt: iso(-2, 14, 30),
  },
  {
    id: 'sp-003',
    accountId: 'acc-001',
    status: 'failed',
    postType: 'feed',
    caption: 'Studio session warmup — deep minimal techno. Building blocks for the next album.',
    imageMinioPath: 'social/sp-003.jpg',
    scheduledAtUtc: iso(-1, 18, 0),
    timezoneName: 'Europe/Berlin',
    retryCount: 2,
    nextRetryAt: iso(0, 15, 0),
    lastError: 'SYNC ERROR — Instagram API rate limit exceeded',
    createdAt: iso(-3, 9, 0),
    updatedAt: iso(-1, 18, 5),
  },
  {
    id: 'sp-004',
    accountId: 'acc-001',
    status: 'published',
    postType: 'feed',
    caption: 'CONFIRMED: Fabric London — Room 1 — April 26. Tickets link in bio 🏴 #fabric #london #techno',
    imageMinioPath: 'social/sp-004.jpg',
    scheduledAtUtc: iso(-5, 12, 0),
    timezoneName: 'Europe/Berlin',
    retryCount: 0,
    nextRetryAt: null,
    lastError: '',
    createdAt: iso(-7, 11, 0),
    updatedAt: iso(-5, 12, 3),
  },
  {
    id: 'sp-005',
    accountId: 'acc-001',
    status: 'published',
    postType: 'story',
    caption: 'Studio session today — new tracks incoming 🎛️ #studio #techno #production',
    imageMinioPath: 'social/sp-005.jpg',
    scheduledAtUtc: iso(-8, 16, 30),
    timezoneName: 'Europe/Berlin',
    retryCount: 0,
    nextRetryAt: null,
    lastError: '',
    createdAt: iso(-10, 15, 0),
    updatedAt: iso(-8, 16, 32),
  },
  {
    id: 'sp-006',
    accountId: 'acc-001',
    status: 'scheduled',
    postType: 'feed',
    caption: 'Berghain prep — Crate digging sessions. Every track earns its place. 🔩 #berghain #techno #cratedigging',
    imageMinioPath: 'social/sp-006.jpg',
    scheduledAtUtc: iso(10, 21, 0),
    timezoneName: 'Europe/Berlin',
    retryCount: 0,
    nextRetryAt: null,
    lastError: '',
    createdAt: iso(0, 8, 0),
    updatedAt: iso(0, 8, 0),
  },
  {
    id: 'sp-007',
    accountId: 'acc-001',
    status: 'published',
    postType: 'feed',
    caption: 'Ostgut Ton royalties statement just dropped — quarter 1 looking strong 💿 #ostgutton #music #royalties',
    imageMinioPath: 'social/sp-007.jpg',
    scheduledAtUtc: iso(-12, 14, 0),
    timezoneName: 'Europe/Berlin',
    retryCount: 0,
    nextRetryAt: null,
    lastError: '',
    createdAt: iso(-14, 13, 0),
    updatedAt: iso(-12, 14, 1),
  },
]

export default defineEventHandler(() => {
  return { data: MOCK_POSTS }
})
