#!/usr/bin/env bash
# Generate Plunk secrets on first install. Idempotent: safe to re-run.
#
# Plunk requires an AUTH_SECRET (used to sign project API tokens) and an
# admin email/password for the first-run UI. This script writes both to
# secrets/email.env (gitignored, alongside secrets/dev.env).
#
# Usage:
#   ./scripts/plunk-bootstrap.sh
#
# Side effects:
#   - Creates secrets/email.env with PLUNK_AUTH_SECRET, PLUNK_ADMIN_EMAIL,
#     PLUNK_ADMIN_PASSWORD, PLUNK_PROJECT_ID (left blank — set this after
#     first login via http://localhost:3030).
#   - Prints a one-liner that pipes the file into secrets/email.env.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
cd "$ROOT"

SECRETS_FILE="secrets/email.env"
mkdir -p secrets

# Auth secret: random 32-byte base64 (Plunk uses this to sign JWTs).
gen_secret() {
  LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 64
}

if [[ ! -f "$SECRETS_FILE" ]]; then
  cat > "$SECRETS_FILE" <<EOF
# Generated by scripts/plunk-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Secrets for self-hosted Plunk (https://github.com/useplunk/plunk).
# Do NOT commit this file.
PLUNK_AUTH_SECRET=$(gen_secret)
PLUNK_ADMIN_EMAIL=admin@klubhub.local
PLUNK_ADMIN_PASSWORD=$(gen_secret)
PLUNK_PROJECT_ID=
PLUNK_API_KEY=
PLUNK_FROM_EMAIL=noreply@klubhub.local
PLUNK_FROM_NAME=KlubHub
PLUNK_PUBLIC_PORT=3030
EOF
  chmod 600 "$SECRETS_FILE"
  echo "wrote $SECRETS_FILE"
else
  echo "$SECRETS_FILE already exists; not overwriting"
fi

# Sanity-check: secrets file is gitignored. Fail loudly if it's been
# re-added so we don't accidentally leak the secret.
if git check-ignore -q "$SECRETS_FILE"; then
  echo "gitignore OK: $SECRETS_FILE is not tracked"
else
  echo "WARN: $SECRETS_FILE is not gitignored — please add 'secrets/' to .gitignore" >&2
  exit 1
fi
