#!/usr/bin/env bash
# Generate Plunk secrets on first install. Idempotent: safe to re-run.
#
# Plunk requires an AUTH_SECRET (used to sign project API tokens) and an
# admin email/password for the first-run UI. This script writes those to
# secrets/email.env (gitignored, alongside secrets/dev.env), and writes the
# project API key into its own single-value file, secrets/plunk_api_key,
# because docker-compose.email.yml mounts it as a dedicated Docker secret
# (a Compose secret mounts as a single file at /run/secrets/<name>, never a
# directory or a multi-value env file).
#
# Usage:
#   ./scripts/plunk-bootstrap.sh
#
# Side effects:
#   - Creates secrets/email.env with PLUNK_AUTH_SECRET, PLUNK_ADMIN_EMAIL,
#     PLUNK_ADMIN_PASSWORD, PLUNK_PROJECT_ID (left blank — set this after
#     first login via http://localhost:3030).
#   - Creates secrets/plunk_api_key (chmod 600, empty placeholder) — mounted
#     at /run/secrets/plunk_api_key on the app service and read via
#     PLUNK_API_KEY_FILE. Paste the project API key from the Plunk admin UI
#     into this file (single line, no trailing newline required) after
#     first login. Override the path with PLUNK_API_KEY_SECRET_FILE if
#     docker-compose.email.yml's PLUNK_API_KEY_SECRET_FILE is set to read
#     it elsewhere.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)"
cd "$ROOT"

SECRETS_FILE="secrets/email.env"
API_KEY_FILE="${PLUNK_API_KEY_SECRET_FILE:-secrets/plunk_api_key}"
mkdir -p secrets "$(dirname "$API_KEY_FILE")"

# Auth secret: random 32-byte base64 (Plunk uses this to sign JWTs).
gen_secret() {
  LC_ALL=C tr -dc 'a-zA-Z0-9' </dev/urandom | head -c 64
}

if [[ ! -f "$SECRETS_FILE" ]]; then
  cat > "$SECRETS_FILE" <<EOF
# Generated by scripts/plunk-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Secrets for self-hosted Plunk (https://github.com/useplunk/plunk).
# Do NOT commit this file.
# The project API key lives in its own file: see $API_KEY_FILE
PLUNK_AUTH_SECRET=$(gen_secret)
PLUNK_ADMIN_EMAIL=admin@klubhub.local
PLUNK_ADMIN_PASSWORD=$(gen_secret)
PLUNK_PROJECT_ID=
PLUNK_FROM_EMAIL=noreply@klubhub.local
PLUNK_FROM_NAME=KlubHub
PLUNK_PUBLIC_PORT=3030
EOF
  chmod 600 "$SECRETS_FILE"
  echo "wrote $SECRETS_FILE"
else
  echo "$SECRETS_FILE already exists; not overwriting"
fi

if [[ ! -f "$API_KEY_FILE" ]]; then
  # Empty placeholder: operators paste the real key in after first login.
  : > "$API_KEY_FILE"
  chmod 600 "$API_KEY_FILE"
  echo "wrote $API_KEY_FILE (empty placeholder — paste the Plunk project API key here)"
else
  echo "$API_KEY_FILE already exists; not overwriting"
fi

# Sanity-check: secrets files are gitignored. Fail loudly if either has been
# re-added so we don't accidentally leak a secret.
for f in "$SECRETS_FILE" "$API_KEY_FILE"; do
  if git check-ignore -q "$f"; then
    echo "gitignore OK: $f is not tracked"
  else
    echo "WARN: $f is not gitignored — please add 'secrets/' to .gitignore" >&2
    exit 1
  fi
done
