<script setup lang="ts">
import type { Tracklist } from '../../types/tracklist';
import type { PresetColors } from '@/utils/design-tokens';

defineProps({
  tracklist: {
    type: Object as () => Tracklist,
    required: true,
  },
  colors: {
    type: Object as () => PresetColors,
    required: true,
  },
});
</script>

<template>
  <div
    style="
      position: absolute;
      bottom: 40px;
      left: 40px;
      right: 40px;
      text-align: center;
      font-size: 18px;
      opacity: 0.7;
    "
  >
    Generated by KlubHub DJ
  </div>
</template>
