<script setup lang="ts">
import type { Tracklist } from '../../types/tracklist';
import type { PresetColors } from '@/utils/design-tokens';

defineProps({
  tracklist: {
    type: Object as () => Tracklist,
    required: true,
  },
  colors: {
    type: Object as () => PresetColors,
    required: true,
  },
});
</script>

<template>
  <div
    :style="{
      position: 'absolute',
      bottom: '40px',
      left: '40px',
      right: '40px',
      textAlign: 'center',
      fontSize: '18px',
      opacity: 0.7,
      color: colors.text,
      fontFamily: 'var(--font-data)',
    }"
  >
    Generated by KlubHub DJ
  </div>
</template>
