-- +goose Up
-- P2.3: the offline door (.claude/plans/promoter-p2-guests-door.plan.md,
-- "P2.3 contract"). Door devices queue check-ins while offline and sync them
-- in batches; every row carries the device's client nonce, so a batch sent
-- twice is applied once. Rows from different devices for the same guest are
-- all kept; the later one points at the earlier one through conflict_of so
-- the door can flag a double entry after sync.

-- Door PINs: a second, manager PIN per event gates on-the-spot adds. Its row
-- also holds a sealed PBKDF2 verifier the device checks offline; the server
-- re-verifies every add against the Argon2id hash. Door login only accepts
-- the staff row (manager = false).
ALTER TABLE door_pins ADD COLUMN manager BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE door_pins ADD COLUMN check_enc BYTEA;
ALTER TABLE door_pins DROP CONSTRAINT door_pins_pkey;
ALTER TABLE door_pins ADD PRIMARY KEY (tenant_id, event_id, manager);
ALTER TABLE door_pins ADD CONSTRAINT door_pins_check_only_manager CHECK (manager OR check_enc IS NULL);
COMMENT ON COLUMN door_pins.manager IS 'data_class: internal — true for the manager PIN that gates on-the-spot adds';
COMMENT ON COLUMN door_pins.failed_attempts IS 'data_class: internal — lockout counter';

CREATE TABLE checkins (
    id            UUID PRIMARY KEY,
    tenant_id     UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    event_id      UUID NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    guest_id      UUID REFERENCES guests (id) ON DELETE CASCADE,
    position_id   UUID REFERENCES order_positions (id) ON DELETE CASCADE,
    count         SMALLINT NOT NULL CHECK (count BETWEEN 1 AND 50),
    direction     TEXT NOT NULL CHECK (direction IN ('in', 'out')),
    client_nonce  TEXT NOT NULL CHECK (length(client_nonce) BETWEEN 8 AND 64),
    device_id     UUID NOT NULL REFERENCES door_devices (id),
    at            TIMESTAMPTZ NOT NULL,
    received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    undone_at     TIMESTAMPTZ,
    undo_nonce    TEXT CHECK (undo_nonce IS NULL OR length(undo_nonce) BETWEEN 8 AND 64),
    conflict_of   UUID REFERENCES checkins (id) ON DELETE SET NULL,
    CHECK ((guest_id IS NULL) <> (position_id IS NULL)),
    UNIQUE (tenant_id, client_nonce)
);
CREATE INDEX checkins_by_event ON checkins (tenant_id, event_id, received_at);
CREATE INDEX checkins_by_guest ON checkins (tenant_id, guest_id) WHERE guest_id IS NOT NULL;
CREATE INDEX checkins_by_position ON checkins (tenant_id, position_id) WHERE position_id IS NOT NULL;
CREATE UNIQUE INDEX checkins_undo_nonce ON checkins (tenant_id, undo_nonce) WHERE undo_nonce IS NOT NULL;
ALTER TABLE checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE checkins FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON checkins
    USING (tenant_id = current_setting('app.tenant_id')::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
GRANT SELECT, INSERT, UPDATE ON checkins TO klubhub_app;
COMMENT ON TABLE checkins IS 'data_class: personal';
COMMENT ON COLUMN checkins.count IS 'data_class: internal — heads admitted by this row (partial +N arrivals), not identifying';
COMMENT ON COLUMN checkins.direction IS 'data_class: internal — in or out';
COMMENT ON COLUMN checkins.client_nonce IS 'data_class: internal — random idempotency key generated by the door device';
COMMENT ON COLUMN checkins.at IS 'data_class: internal — the door device''s clock when the check-in happened';
COMMENT ON COLUMN checkins.undo_nonce IS 'data_class: internal — idempotency key of the undo op that cancelled this row';
COMMENT ON COLUMN checkins.conflict_of IS 'data_class: internal — the earlier row from another device this one double-counts';

CREATE TABLE door_counters (
    id            UUID PRIMARY KEY,
    tenant_id     UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    event_id      UUID NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    device_id     UUID NOT NULL REFERENCES door_devices (id),
    kind          TEXT NOT NULL CHECK (kind IN ('walkup', 'in', 'out')),
    delta         SMALLINT NOT NULL CHECK (delta BETWEEN 1 AND 50),
    client_nonce  TEXT NOT NULL CHECK (length(client_nonce) BETWEEN 8 AND 64),
    at            TIMESTAMPTZ NOT NULL,
    received_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    undone_at     TIMESTAMPTZ,
    undo_nonce    TEXT CHECK (undo_nonce IS NULL OR length(undo_nonce) BETWEEN 8 AND 64),
    UNIQUE (tenant_id, client_nonce)
);
CREATE INDEX door_counters_by_event ON door_counters (tenant_id, event_id, received_at);
CREATE UNIQUE INDEX door_counters_undo_nonce ON door_counters (tenant_id, undo_nonce) WHERE undo_nonce IS NOT NULL;
ALTER TABLE door_counters ENABLE ROW LEVEL SECURITY;
ALTER TABLE door_counters FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON door_counters
    USING (tenant_id = current_setting('app.tenant_id')::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
GRANT SELECT, INSERT, UPDATE ON door_counters TO klubhub_app;
COMMENT ON TABLE door_counters IS 'data_class: internal';
COMMENT ON COLUMN door_counters.kind IS 'data_class: internal — walk-up (paid at the door) or a manual in/out adjustment';

-- +goose Down
DROP TABLE IF EXISTS door_counters;
DROP TABLE IF EXISTS checkins;
DELETE FROM door_pins WHERE manager;
ALTER TABLE door_pins DROP CONSTRAINT door_pins_check_only_manager;
ALTER TABLE door_pins DROP CONSTRAINT door_pins_pkey;
ALTER TABLE door_pins ADD PRIMARY KEY (tenant_id, event_id);
ALTER TABLE door_pins DROP COLUMN check_enc;
ALTER TABLE door_pins DROP COLUMN manager;
