-- +goose Up
-- P2.6: the sealed tier and the ban list (.claude/plans/promoter-p2-guests-door.plan.md,
-- "P2.6 contract"; ADR 0001 class `sealed`). Everything sealed here is
-- encrypted in the browser: the server stores X25519 public keys and opaque
-- ciphertext (`*_sealed`), checks their structure only and has no way to
-- decrypt them. The organisation's sealed key (OSK) exists only as wraps
-- sealed to members' keys, door devices' keys and the recovery key.

-- Door devices generate their own X25519 keypair at registration and send
-- the public key; the private key never leaves the device.
ALTER TABLE door_devices ADD COLUMN public_key BYTEA
    CHECK (public_key IS NULL OR octet_length(public_key) = 32);
COMMENT ON COLUMN door_devices.public_key IS 'data_class: internal — X25519 public key generated by the door device (sealed tier)';

-- One X25519 keypair per member. The private key is sealed in the browser
-- under Argon2id(passphrase); kdf holds its public parameters.
CREATE TABLE member_keys (
    tenant_id       UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    user_id         UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    public_key      BYTEA NOT NULL CHECK (octet_length(public_key) = 32),
    private_sealed  BYTEA NOT NULL CHECK (octet_length(private_sealed) BETWEEN 61 AND 512 AND get_byte(private_sealed, 0) = 1),
    kdf             JSONB NOT NULL CHECK (kdf ->> 'alg' = 'argon2id'),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (tenant_id, user_id)
);
ALTER TABLE member_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE member_keys FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON member_keys
    USING (tenant_id = current_setting('app.tenant_id')::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON member_keys TO klubhub_app;
COMMENT ON TABLE member_keys IS 'data_class: internal';
COMMENT ON COLUMN member_keys.public_key IS 'data_class: internal — X25519 public key';
COMMENT ON COLUMN member_keys.private_sealed IS 'data_class: internal — private key sealed in the browser under the member''s passphrase; the server cannot open it';
COMMENT ON COLUMN member_keys.kdf IS 'data_class: internal — public Argon2id parameters and salt';

-- Versions of the organisation's sealed key. At most one is active; the
-- recovery public key and fingerprint belong to the recovery kit.
CREATE TABLE org_sealed_keys (
    tenant_id             UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    version               INTEGER NOT NULL CHECK (version >= 1),
    status                TEXT NOT NULL CHECK (status IN ('active', 'retired')),
    recovery_public_key   BYTEA NOT NULL CHECK (octet_length(recovery_public_key) = 32),
    recovery_fingerprint  TEXT NOT NULL CHECK (recovery_fingerprint ~ '^[0-9a-f]{16}$'),
    created_by            UUID REFERENCES users (id) ON DELETE SET NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    retired_at            TIMESTAMPTZ,
    PRIMARY KEY (tenant_id, version),
    CHECK ((status = 'retired') = (retired_at IS NOT NULL))
);
CREATE UNIQUE INDEX org_sealed_keys_one_active ON org_sealed_keys (tenant_id) WHERE status = 'active';
ALTER TABLE org_sealed_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_sealed_keys FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON org_sealed_keys
    USING (tenant_id = current_setting('app.tenant_id')::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
GRANT SELECT, INSERT, UPDATE ON org_sealed_keys TO klubhub_app;
COMMENT ON TABLE org_sealed_keys IS 'data_class: internal';
COMMENT ON COLUMN org_sealed_keys.status IS 'data_class: internal — active or retired';
COMMENT ON COLUMN org_sealed_keys.recovery_public_key IS 'data_class: internal — X25519 public key of the recovery kit';
COMMENT ON COLUMN org_sealed_keys.recovery_fingerprint IS 'data_class: internal — first 8 bytes of SHA-256(recovery public key), hex';
COMMENT ON COLUMN org_sealed_keys.created_by IS 'data_class: internal — user id reference';

-- The OSK sealed to one recipient: a member (user id), a door device
-- (device id) or the recovery key (no id). One wrap per recipient and
-- version; the expression index makes the recovery wrap unique too.
CREATE TABLE org_key_wraps (
    id              UUID PRIMARY KEY,
    tenant_id       UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    version         INTEGER NOT NULL,
    recipient_kind  TEXT NOT NULL CHECK (recipient_kind IN ('member', 'device', 'recovery')),
    recipient_id    UUID,
    wrap_sealed     BYTEA NOT NULL CHECK (octet_length(wrap_sealed) BETWEEN 93 AND 256 AND get_byte(wrap_sealed, 0) = 1),
    created_by      UUID REFERENCES users (id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, version) REFERENCES org_sealed_keys (tenant_id, version) ON DELETE CASCADE,
    CHECK ((recipient_kind = 'recovery') = (recipient_id IS NULL))
);
CREATE UNIQUE INDEX org_key_wraps_recipient ON org_key_wraps
    (tenant_id, version, recipient_kind, COALESCE(recipient_id, '00000000-0000-0000-0000-000000000000'::uuid));
CREATE INDEX org_key_wraps_by_recipient ON org_key_wraps (tenant_id, recipient_kind, recipient_id);
ALTER TABLE org_key_wraps ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_key_wraps FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON org_key_wraps
    USING (tenant_id = current_setting('app.tenant_id')::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON org_key_wraps TO klubhub_app;
COMMENT ON TABLE org_key_wraps IS 'data_class: internal';
COMMENT ON COLUMN org_key_wraps.recipient_kind IS 'data_class: internal — member, device or recovery';
COMMENT ON COLUMN org_key_wraps.wrap_sealed IS 'data_class: internal — the OSK sealed in the browser to the recipient''s public key';
COMMENT ON COLUMN org_key_wraps.created_by IS 'data_class: internal — user id reference';

-- Set when someone who held the OSK loses access (member removed, door
-- device revoked): the owner should rotate. Cleared by a rotation.
CREATE TABLE org_key_state (
    tenant_id         UUID NOT NULL PRIMARY KEY REFERENCES organizations (id) ON DELETE CASCADE,
    rotation_pending  BOOLEAN NOT NULL DEFAULT false,
    rotation_reason   TEXT CHECK (rotation_reason IN ('member_removed', 'device_revoked')),
    pending_since     TIMESTAMPTZ,
    CHECK (rotation_pending = (rotation_reason IS NOT NULL)),
    CHECK (rotation_pending = (pending_since IS NOT NULL))
);
ALTER TABLE org_key_state ENABLE ROW LEVEL SECURITY;
ALTER TABLE org_key_state FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON org_key_state
    USING (tenant_id = current_setting('app.tenant_id')::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
GRANT SELECT, INSERT, UPDATE ON org_key_state TO klubhub_app;
COMMENT ON TABLE org_key_state IS 'data_class: internal';
COMMENT ON COLUMN org_key_state.rotation_pending IS 'data_class: internal — the OSK should be rotated';
COMMENT ON COLUMN org_key_state.rotation_reason IS 'data_class: internal — member_removed or device_revoked';

-- The ban list: each entry is sealed in the browser under the OSK version
-- key_version. Only the expiry is plaintext, so the retention job can
-- delete expired entries.
CREATE TABLE ban_entries (
    id            UUID PRIMARY KEY,
    tenant_id     UUID NOT NULL REFERENCES organizations (id) ON DELETE CASCADE,
    key_version   INTEGER NOT NULL,
    entry_sealed  BYTEA NOT NULL CHECK (octet_length(entry_sealed) BETWEEN 30 AND 4096 AND get_byte(entry_sealed, 0) = 1),
    expires_at    TIMESTAMPTZ NOT NULL,
    created_by    UUID REFERENCES users (id) ON DELETE SET NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    FOREIGN KEY (tenant_id, key_version) REFERENCES org_sealed_keys (tenant_id, version)
);
CREATE INDEX ban_entries_expiry ON ban_entries (tenant_id, expires_at);
ALTER TABLE ban_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE ban_entries FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON ban_entries
    USING (tenant_id = current_setting('app.tenant_id')::uuid)
    WITH CHECK (tenant_id = current_setting('app.tenant_id')::uuid);
GRANT SELECT, INSERT, UPDATE, DELETE ON ban_entries TO klubhub_app;
COMMENT ON TABLE ban_entries IS 'data_class: personal';
COMMENT ON COLUMN ban_entries.created_by IS 'data_class: internal — user id of the staff member who added the entry (a reference, not the banned person)';

-- +goose Down
DROP TABLE IF EXISTS ban_entries;
DROP TABLE IF EXISTS org_key_state;
DROP TABLE IF EXISTS org_key_wraps;
DROP TABLE IF EXISTS org_sealed_keys;
DROP TABLE IF EXISTS member_keys;
ALTER TABLE door_devices DROP COLUMN IF EXISTS public_key;
